"""
族群寶：題材元資料
每個族群的介紹、CAGR、市場規模、關鍵指標、icon 色彩
沒有在 META 中的族群，build_site 會自動補簡版資料。
最後更新: 2026-04-24
"""

INDUSTRY_META = {
    # ═══════════════════════════════════════════
    #  AI / 半導體核心
    # ═══════════════════════════════════════════
    "CPU 概念股": {
        "en": "CPU Supply Chain",
        "category": "AI / 半導體",
        "color": "#0071c5",
        "desc": "Intel/AMD CPU 短缺崛起族群（2026 Q2 Lisa Su 確認需求遠超預期）。"
                "祥碩 (AMD USB pure-play)、信驊 (Server BMC 全球第一)、欣興/南電/景碩 (CPU ABF 載板三雄)、"
                "嘉澤 (LGA Socket)、日月光投控 (CPU 封測)、華碩/技嘉/微星/華擎 (主機板)、"
                "矽力*-KY (DDR5 PMIC)、奇鋐/雙鴻 (CPU 散熱)、台達電 (CPU VRM) 為核心受惠台廠。",
        "cagr": "20%",
        "market_size": "180B USD",
        "indicators": [
            {"label": "事件", "value": "Intel/AMD CPU 短缺"},
            {"label": "AMD pure-play", "value": "祥碩 / 信驊"},
            {"label": "ABF 載板", "value": "欣興 / 南電 / 景碩"},
            {"label": "毛利", "value": "封測 30% / 載板 25%"},
        ],
    },
    "AI伺服器": {
        "en": "AI Server",
        "category": "AI / 半導體",
        "color": "#ff7847",
        "desc": "以 NVIDIA GB200/300 平台為核心，整合 GPU、HBM、液冷、BBU 電源模組的高密度運算伺服器。"
                "台廠ODM 取得全球 AI 伺服器代工 9 成以上，是 AI 資本支出最直接的受益者。",
        "cagr": "35%+",
        "market_size": "300B USD",
        "indicators": [
            {"label": "資本支出驅動", "value": "北美 4 大 CSP"},
            {"label": "關鍵技術", "value": "液冷 / 800V HVDC"},
            {"label": "核心客戶", "value": "Meta / Google / AWS / Azure"},
            {"label": "台廠地位", "value": "全球代工 > 90%"},
        ],
    },
    "輝達概念股": {
        "en": "NVIDIA Supply Chain",
        "category": "AI / 半導體",
        "color": "#76b900",
        "desc": "NVIDIA GPU 供應鏈，從台積電代工、日月光封測、到緯創/鴻海/廣達組裝，"
                "貫穿整個 AI 產業價值鏈。GB300/Rubin 世代量產拉貨動能延續。",
        "cagr": "40%+",
        "market_size": "150B USD",
        "indicators": [
            {"label": "產品世代", "value": "GB300 / Rubin"},
            {"label": "營收占比", "value": "台廠 AI 營收主力"},
            {"label": "核心客戶", "value": "NVIDIA DC 部門"},
            {"label": "產業地位", "value": "GPU 代工獨占"},
        ],
    },
    "Google TPU": {
        "en": "Google TPU",
        "category": "AI / 半導體",
        "color": "#4285f4",
        "desc": "Google 自研 TPU 晶片供應鏈，由世芯-KY/創意設計服務切入，延伸至先進封裝與 HBM。"
                "CSP 自研晶片去輝達化趨勢中的主要受益者。",
        "cagr": "50%+",
        "market_size": "30B USD",
        "indicators": [
            {"label": "世代", "value": "TPU v6 / v7"},
            {"label": "設計服務", "value": "世芯 / 創意"},
            {"label": "核心客戶", "value": "Google"},
            {"label": "驗證趨勢", "value": "去 NVIDIA 化"},
        ],
    },
    "ASIC/IP矽智財": {
        "en": "ASIC & IP Design",
        "category": "AI / 半導體",
        "color": "#ff7847",
        "desc": "隨著 CSP 積極推動「去輝達化」與晶片自研，ASIC（客製化晶片）與 IP（矽智財）"
                "成為 AI 算力落地的核心。聚焦 3nm/2nm 先進製程設計服務、先進封裝整合。",
        "cagr": "30%+",
        "market_size": "18.5B USD",
        "indicators": [
            {"label": "技術節點", "value": "3nm 量產 / 2nm 送樣"},
            {"label": "營收模式", "value": "NRE 向 Turnkey 轉型"},
            {"label": "核心客戶", "value": "北美 CSP 與 AI 系統廠"},
            {"label": "產業地位", "value": "半導體價值鏈最頂端"},
        ],
    },
    "IC設計": {
        "en": "IC Design",
        "category": "AI / 半導體",
        "color": "#5b8def",
        "desc": "涵蓋聯發科、聯詠、瑞昱等 IC 設計龍頭，產品橫跨手機 SoC、顯示 IC、網通、周邊控制。"
                "2026 年受惠 AI PC、AI 手機邊緣運算需求。",
        "cagr": "12%",
        "market_size": "90B USD",
        "indicators": [
            {"label": "製程", "value": "3nm / 4nm"},
            {"label": "應用", "value": "SoC / 網通 / 顯示"},
            {"label": "客戶", "value": "OEM / ODM"},
            {"label": "產業地位", "value": "台灣 IC 設計產值全球 #2"},
        ],
    },
    "AI PC/邊緣AI": {
        "en": "AI PC / Edge AI",
        "category": "AI / 半導體",
        "color": "#8b5cf6",
        "desc": "搭載 NPU 的 AI PC 滲透率從 2025 的 20% 往 2027 年 60% 以上滲透，"
                "帶動 ODM、SoC、散熱、記憶體全面升級。",
        "cagr": "25%",
        "market_size": "60B USD",
        "indicators": [
            {"label": "滲透率", "value": "2027E 60%+"},
            {"label": "NPU TOPS", "value": "40 TOPS 門檻"},
            {"label": "核心 OS", "value": "Windows Copilot+"},
            {"label": "台廠優勢", "value": "ODM 全球龍頭"},
        ],
    },

    # ═══════════════════════════════════════════
    #  封裝 / 測試
    # ═══════════════════════════════════════════
    "CoWoS先進封裝": {
        "en": "CoWoS Advanced Packaging",
        "category": "封裝 / 測試",
        "color": "#f97316",
        "desc": "台積電主導的 2.5D 先進封裝技術，將 GPU/ASIC 與 HBM 整合在同一矽中介層。"
                "2026 年台積電 CoWoS 月產能上看 9 萬片，受益設備、載板、測試鏈。",
        "cagr": "45%",
        "market_size": "25B USD",
        "indicators": [
            {"label": "月產能", "value": "2026E 90K 片"},
            {"label": "瓶頸", "value": "中介層供應"},
            {"label": "核心製程", "value": "InFO / SoIC"},
            {"label": "台廠卡位", "value": "全面受惠"},
        ],
    },
    "半導體設備": {
        "en": "Semiconductor Equipment",
        "category": "封裝 / 測試",
        "color": "#06b6d4",
        "desc": "廠務工程、濕製程、測試設備供應鏈。受益台積電 A14/A16 擴產與 CoWoS 產能倍增。",
        "cagr": "15%",
        "market_size": "120B USD",
        "indicators": [
            {"label": "客戶", "value": "TSMC / 聯電 / 力積電"},
            {"label": "擴產週期", "value": "2025-2028"},
            {"label": "國產化率", "value": "持續提升"},
            {"label": "進入門檻", "value": "潔淨室認證"},
        ],
    },
    "檢測/設備服務": {
        "en": "Testing & Equipment Services",
        "category": "封裝 / 測試",
        "color": "#14b8a6",
        "desc": "探針卡、測試座、AOI、故障分析、晶圓再生等半導體檢測服務。先進封裝拉動測試設備需求。",
        "cagr": "20%",
        "market_size": "15B USD",
        "indicators": [
            {"label": "驅動", "value": "先進封裝 / HBM"},
            {"label": "核心技術", "value": "MEMS 探針"},
            {"label": "客戶", "value": "封測廠 / 晶圓廠"},
            {"label": "壁壘", "value": "認證週期 1-2 年"},
        ],
    },

    # ═══════════════════════════════════════════
    #  基板 / PCB
    # ═══════════════════════════════════════════
    "PCB/銅箔基板": {
        "en": "PCB / CCL",
        "category": "基板 / PCB",
        "color": "#ef4444",
        "desc": "HVLP4 高階銅箔、低 Dk/Df CCL 為 GB300 世代關鍵材料。2026-2027 年供需缺口 40%+。",
        "cagr": "18%",
        "market_size": "80B USD",
        "indicators": [
            {"label": "關鍵材料", "value": "HVLP4 銅箔"},
            {"label": "供需缺口", "value": "2026 -48%"},
            {"label": "價格", "value": "Q1 季增 10-40%"},
            {"label": "受惠公司", "value": "台光電 / 台燿"},
        ],
    },
    "ABF載板": {
        "en": "ABF Substrate",
        "category": "基板 / PCB",
        "color": "#dc2626",
        "desc": "高階 CPU/GPU 封裝必備載板。三雄欣興、南電、景碩受惠 AI 晶片世代升級。",
        "cagr": "15%",
        "market_size": "12B USD",
        "indicators": [
            {"label": "寡占", "value": "台日韓 5 家"},
            {"label": "產能週期", "value": "2026 新廠開出"},
            {"label": "核心客戶", "value": "Intel / NVIDIA / AMD"},
            {"label": "技術", "value": "層數 18+ / 大尺寸"},
        ],
    },
    "玻璃基板": {
        "en": "Glass Core Substrate",
        "category": "基板 / PCB",
        "color": "#a855f7",
        "desc": "繼 CoWoS 之後先進封裝關鍵戰場，旨在解決 AI 晶片高功耗下的散熱與傳輸瓶頸，"
                "預計 2026 年進入試產、2027 年量產。",
        "cagr": "80%+",
        "market_size": "5B USD",
        "indicators": [
            {"label": "試產時程", "value": "2026 Q3"},
            {"label": "技術節點", "value": "TGV 穿孔 / RDL"},
            {"label": "核心玩家", "value": "Intel / 三星"},
            {"label": "台廠切入", "value": "欣興 / 台光電"},
        ],
    },

    # ═══════════════════════════════════════════
    #  散熱 / 電源
    # ═══════════════════════════════════════════
    "散熱/液冷": {
        "en": "Thermal / Liquid Cooling",
        "category": "散熱 / 電源",
        "color": "#0ea5e9",
        "desc": "GB200 採水冷 CDU、冷板、快接頭等液冷方案，單伺服器散熱 BOM 較風冷提升 5-8 倍。",
        "cagr": "60%",
        "market_size": "8B USD",
        "indicators": [
            {"label": "滲透率", "value": "2026E 35%"},
            {"label": "ASP 提升", "value": "x5-8 vs 風冷"},
            {"label": "台廠地位", "value": "奇鋐 / 雙鴻 / 高力"},
            {"label": "技術趨勢", "value": "CDU / 浸沒式"},
        ],
    },
    "電源供應器/BBU": {
        "en": "Power Supply / BBU",
        "category": "散熱 / 電源",
        "color": "#eab308",
        "desc": "AI 伺服器 PSU 從 3kW 升級至 12kW，BBU 備用電池模組是 AI 機櫃必備。"
                "台達電、光寶科為核心玩家。",
        "cagr": "30%",
        "market_size": "15B USD",
        "indicators": [
            {"label": "ASP 提升", "value": "3kW → 12kW"},
            {"label": "BBU 滲透率", "value": "2026E 50%"},
            {"label": "核心客戶", "value": "NVIDIA / CSP"},
            {"label": "台廠", "value": "台達 / 光寶 / 群電"},
        ],
    },
    "重電": {
        "en": "Heavy Electrical",
        "category": "散熱 / 電源",
        "color": "#f59e0b",
        "desc": "AI 資料中心耗電暴增帶動重電設備需求，台電 2025-2030 強韌電網預算 5,645 億。"
                "士電、中興電、華城受惠。",
        "cagr": "25%",
        "market_size": "20B USD",
        "indicators": [
            {"label": "台電預算", "value": "5,645 億"},
            {"label": "週期", "value": "2025-2030"},
            {"label": "驅動力", "value": "AI DC + 電動車"},
            {"label": "訂單能見度", "value": "3-5 年"},
        ],
    },
    "HVDC/直流電力": {
        "en": "HVDC Power",
        "category": "散熱 / 電源",
        "color": "#d97706",
        "desc": "NVIDIA 800V HVDC 新架構，大幅減少銅線用量。台達電、士電卡位受益。",
        "cagr": "100%+",
        "market_size": "3B USD",
        "indicators": [
            {"label": "規格", "value": "800V DC"},
            {"label": "推動者", "value": "NVIDIA"},
            {"label": "台廠", "value": "台達 / 士電"},
            {"label": "時程", "value": "2026 導入"},
        ],
    },

    # ═══════════════════════════════════════════
    #  光通訊 / 網通 / 衛星
    # ═══════════════════════════════════════════
    "光通訊/CPO": {
        "en": "Silicon Photonics & CPO",
        "category": "光通訊 / 網通",
        "color": "#10b981",
        "desc": "半導體異質整合的尖端技術，將光通訊元件與邏輯晶片共同封裝 (Co-Packaged Optics)，"
                "解決 AI 叢集對頻寬與功耗的需求。2026 為量產元年。",
        "cagr": "70%+",
        "market_size": "12B USD",
        "indicators": [
            {"label": "量產時程", "value": "2026 商轉"},
            {"label": "頻寬世代", "value": "1.6T / 3.2T"},
            {"label": "核心客戶", "value": "NVIDIA / Broadcom"},
            {"label": "矽光子七劍客", "value": "聯亞 / 全新 / 波若威等"},
        ],
    },
    "矽光子": {
        "en": "Silicon Photonics",
        "category": "光通訊 / 網通",
        "color": "#059669",
        "desc": "以矽製程製造光通訊晶片，是 CPO 的上游核心。台積電 COUPE 平台、穩懋、聯亞深度切入。",
        "cagr": "65%",
        "market_size": "8B USD",
        "indicators": [
            {"label": "核心平台", "value": "TSMC COUPE"},
            {"label": "關鍵材料", "value": "InP / Si"},
            {"label": "台廠領先", "value": "穩懋 / 聯亞"},
            {"label": "導入時程", "value": "2026 量產"},
        ],
    },
    "高速傳輸": {
        "en": "High-Speed Interconnect",
        "category": "光通訊 / 網通",
        "color": "#34d399",
        "desc": "CXL、PCIe 6.0、224G SerDes 等高速介面，AI 叢集內部互連關鍵。",
        "cagr": "40%",
        "market_size": "18B USD",
        "indicators": [
            {"label": "規格", "value": "PCIe 6.0 / 224G"},
            {"label": "應用", "value": "AI 叢集互連"},
            {"label": "台廠 IP", "value": "威鋒 / 譜瑞"},
            {"label": "認證週期", "value": "12-18 月"},
        ],
    },
    "低軌衛星": {
        "en": "LEO Satellite",
        "category": "光通訊 / 網通",
        "color": "#22d3ee",
        "desc": "Starlink、Kuiper、OneWeb 三大星系帶動地面設備需求。台廠在天線、功放、地面站有優勢。",
        "cagr": "35%",
        "market_size": "40B USD",
        "indicators": [
            {"label": "星系", "value": "Starlink / Kuiper"},
            {"label": "台廠卡位", "value": "昇達 / 啟碁 / 華星光"},
            {"label": "政策支持", "value": "國防通訊"},
            {"label": "訂單能見度", "value": "3-5 年"},
        ],
    },
    "網通": {
        "en": "Networking",
        "category": "光通訊 / 網通",
        "color": "#0d9488",
        "desc": "WiFi 7、Switch、企業網通設備。AI 資料中心帶動高階 Switch 需求。",
        "cagr": "15%",
        "market_size": "50B USD",
        "indicators": [
            {"label": "世代", "value": "WiFi 7 / 800G Switch"},
            {"label": "應用", "value": "CSP / 企業 / 家用"},
            {"label": "客戶", "value": "Arista / Cisco"},
            {"label": "台廠", "value": "智邦 / 啟碁"},
        ],
    },

    # ═══════════════════════════════════════════
    #  連接器 / 被動 / 記憶體
    # ═══════════════════════════════════════════
    "連接器": {
        "en": "Connectors",
        "category": "連接器 / 被動",
        "color": "#6366f1",
        "desc": "AI 伺服器內部高速連接器、電源連接器單機 BOM 大幅提升。嘉澤、貿聯 KY 為主。",
        "cagr": "25%",
        "market_size": "25B USD",
        "indicators": [
            {"label": "ASP 提升", "value": "x3-5"},
            {"label": "關鍵規格", "value": "224G / 電源"},
            {"label": "台廠龍頭", "value": "嘉澤 / 貿聯"},
            {"label": "進入門檻", "value": "認證嚴格"},
        ],
    },
    "被動元件": {
        "en": "Passive Components",
        "category": "連接器 / 被動",
        "color": "#8b5cf6",
        "desc": "MLCC、電感、電阻等被動元件。AI 伺服器用量暴增、汽車電子需求強。",
        "cagr": "12%",
        "market_size": "20B USD",
        "indicators": [
            {"label": "單伺服器用量", "value": "x3"},
            {"label": "週期位置", "value": "復甦中"},
            {"label": "龍頭", "value": "國巨 / 華新科"},
            {"label": "材料自主", "value": "70%+"},
        ],
    },
    "記憶體": {
        "en": "Memory",
        "category": "AI / 半導體",
        "color": "#a78bfa",
        "desc": "DRAM、NAND Flash。2026 Q1 HBM 缺貨帶動 DDR 價格大漲，南亞科、華邦電受惠。",
        "cagr": "20%",
        "market_size": "180B USD",
        "indicators": [
            {"label": "循環位置", "value": "上升期"},
            {"label": "HBM 滲透", "value": "AI 需求爆發"},
            {"label": "DDR 漲幅", "value": "2026 Q1 +20%"},
            {"label": "台廠", "value": "南亞科 / 華邦 / 群聯"},
        ],
    },

    # ═══════════════════════════════════════════
    #  車用 / 機器人
    # ═══════════════════════════════════════════
    "電動車": {
        "en": "Electric Vehicle",
        "category": "車用 / 機器人",
        "color": "#84cc16",
        "desc": "Tesla、鴻海 MIH、中國新勢力供應鏈。充電樁、電池管理、馬達為三大重點。",
        "cagr": "20%",
        "market_size": "500B USD",
        "indicators": [
            {"label": "滲透率", "value": "2026E 35%"},
            {"label": "核心系統", "value": "BMS / 三電"},
            {"label": "台廠卡位", "value": "鴻海 / 台達"},
            {"label": "成長區域", "value": "美 / 中 / 東南亞"},
        ],
    },
    "車用電子": {
        "en": "Automotive Electronics",
        "category": "車用 / 機器人",
        "color": "#65a30d",
        "desc": "ADAS、智慧座艙、車用晶片。2026 年 L2+ 滲透率突破 60%。",
        "cagr": "18%",
        "market_size": "300B USD",
        "indicators": [
            {"label": "L2+ 滲透", "value": "2026E 60%"},
            {"label": "關鍵晶片", "value": "SoC / MCU"},
            {"label": "台廠", "value": "聯發 / 光寶"},
            {"label": "驗證週期", "value": "3-5 年"},
        ],
    },
    "機器人": {
        "en": "Robotics",
        "category": "車用 / 機器人",
        "color": "#fb923c",
        "desc": "人形機器人 + 工業機器人。Tesla Optimus、Figure 進入商業化擴張點，"
                "線性馬達、減速器、滾珠螺桿為台廠強項。",
        "cagr": "50%+",
        "market_size": "15B USD",
        "indicators": [
            {"label": "人形滲透", "value": "2028 量產"},
            {"label": "關鍵零件", "value": "線性馬達 / 減速器"},
            {"label": "台廠龍頭", "value": "上銀 / 大銀微"},
            {"label": "驅動力", "value": "勞動力短缺 + AI"},
        ],
    },

    # ═══════════════════════════════════════════
    #  國防 / 無人機 / 資安
    # ═══════════════════════════════════════════
    "軍工/國防": {
        "en": "Defense",
        "category": "國防 / 資安",
        "color": "#7c2d12",
        "desc": "國防預算倍增 + 自主國防政策。漢翔、台船、雷虎科技、神基為核心。",
        "cagr": "30%",
        "market_size": "50B USD",
        "indicators": [
            {"label": "國防預算", "value": "GDP 3%+"},
            {"label": "自製率", "value": "持續提升"},
            {"label": "新標案", "value": "2026 起大幅釋出"},
            {"label": "核心公司", "value": "漢翔 / 台船"},
        ],
    },
    "無人機": {
        "en": "Drone / UAV",
        "category": "國防 / 資安",
        "color": "#991b1b",
        "desc": "無人機國家隊政策推動，軍用 + 民用需求並進。雷虎科技、中光電、攸泰切入。",
        "cagr": "45%",
        "market_size": "8B USD",
        "indicators": [
            {"label": "國家隊", "value": "龍德 / 中光電 / 漢翔"},
            {"label": "軍用標案", "value": "2026 擴大"},
            {"label": "民用應用", "value": "物流 / 監測"},
            {"label": "供應鏈自主", "value": "高"},
        ],
    },
    "資安": {
        "en": "Cybersecurity",
        "category": "國防 / 資安",
        "color": "#dc2626",
        "desc": "零信任架構、雲端資安、工控資安。政府預算 + 企業合規雙驅動。",
        "cagr": "20%",
        "market_size": "10B USD",
        "indicators": [
            {"label": "政策", "value": "關鍵基礎設施"},
            {"label": "企業支出", "value": "年增 15%+"},
            {"label": "台廠", "value": "精誠 / 神盾"},
            {"label": "趨勢", "value": "零信任 / AI"},
        ],
    },

    # ═══════════════════════════════════════════
    #  其他
    # ═══════════════════════════════════════════
    "蘋果概念股": {
        "en": "Apple Supply Chain",
        "category": "消費電子",
        "color": "#71717a",
        "desc": "iPhone、Vision Pro、Apple Intelligence 供應鏈。2026 年折疊機 + AI 功能為亮點。",
        "cagr": "8%",
        "market_size": "200B USD",
        "indicators": [
            {"label": "新品", "value": "iPhone 18 / 折疊"},
            {"label": "AI 功能", "value": "Apple Intelligence"},
            {"label": "核心台廠", "value": "鴻海 / 大立光"},
            {"label": "佔營收比", "value": "部分公司 >50%"},
        ],
    },
    "金融股": {
        "en": "Financials",
        "category": "金融",
        "color": "#0369a1",
        "desc": "金控股。2026 年升息循環進入尾聲、壽險匯損壓力緩解，獲利回升。",
        "cagr": "10%",
        "market_size": "—",
        "indicators": [
            {"label": "淨值比", "value": "改善中"},
            {"label": "殖利率", "value": "4-6%"},
            {"label": "壽險", "value": "TW-ICS 過渡"},
            {"label": "現金股利", "value": "2026 回升"},
        ],
    },
    "生技醫療": {
        "en": "Biotech",
        "category": "生技 / 醫療",
        "color": "#16a34a",
        "desc": "新藥、CDMO、疫苗。高端、藥華藥、保瑞為核心。2026 年多個關鍵里程碑。",
        "cagr": "15%",
        "market_size": "—",
        "indicators": [
            {"label": "臨床進度", "value": "多標的 P3"},
            {"label": "CDMO", "value": "保瑞擴廠"},
            {"label": "政策", "value": "健保放寬"},
            {"label": "授權金", "value": "2026 認列"},
        ],
    },
    "觀光餐旅": {
        "en": "Tourism & Hospitality",
        "category": "傳產",
        "color": "#ec4899",
        "desc": "國旅、出境、餐飲回溫。2026 年運動賽事 + 日圓走勢影響。",
        "cagr": "8%",
        "market_size": "—",
        "indicators": [
            {"label": "來台人次", "value": "回到 2019 90%"},
            {"label": "客單價", "value": "提升"},
            {"label": "旅遊平台", "value": "雄獅 / 山富"},
            {"label": "龍頭", "value": "晶華 / 王品"},
        ],
    },
    "面板/顯示器": {
        "en": "Display Panel",
        "category": "面板 / 光電",
        "color": "#7c3aed",
        "desc": "OLED、Mini LED、車用面板。2026 年蘋果擴大 OLED 採用，友達、群創受惠。",
        "cagr": "10%",
        "market_size": "—",
        "indicators": [
            {"label": "技術", "value": "OLED / Mini LED"},
            {"label": "應用", "value": "手機 / 車用 / 電競"},
            {"label": "整併", "value": "持續中"},
            {"label": "台廠", "value": "友達 / 群創"},
        ],
    },
    "LED/光電": {
        "en": "LED / Optics",
        "category": "面板 / 光電",
        "color": "#ea580c",
        "desc": "Mini LED 背光、車用 LED、紅外線感測。",
        "cagr": "12%",
        "market_size": "—",
        "indicators": [
            {"label": "應用", "value": "Mini LED 電視"},
            {"label": "車用 LED", "value": "成長中"},
            {"label": "台廠", "value": "富采 / 榮創"},
            {"label": "趨勢", "value": "Micro LED 試產"},
        ],
    },
    "塑化/原物料": {
        "en": "Petrochemicals",
        "category": "傳產",
        "color": "#525252",
        "desc": "塑化週期股。2026 年中國產能調節 + 需求回升，台塑四寶獲利修復。",
        "cagr": "—",
        "market_size": "—",
        "indicators": [
            {"label": "週期位置", "value": "谷底回升"},
            {"label": "中國供給", "value": "產能整併"},
            {"label": "殖利率", "value": "5-8%"},
            {"label": "核心", "value": "台塑四寶"},
        ],
    },
    "航運/貨櫃": {
        "en": "Container Shipping",
        "category": "航運 / 傳產",
        "color": "#1d4ed8",
        "desc": "紅海危機、巴拿馬運河限制推升運價。長榮、陽明、萬海為主。",
        "cagr": "—",
        "market_size": "—",
        "indicators": [
            {"label": "SCFI 指數", "value": "強勢"},
            {"label": "油耗規範", "value": "新船替換"},
            {"label": "台廠", "value": "長榮 / 陽明"},
            {"label": "週期位置", "value": "高檔盤整"},
        ],
    },
    "航運/散裝": {
        "en": "Dry Bulk Shipping",
        "category": "航運 / 傳產",
        "color": "#2563eb",
        "desc": "BDI 散裝運價指數走高，鐵礦砂、煤炭、穀物運輸需求強勁。",
        "cagr": "—",
        "market_size": "—",
        "indicators": [
            {"label": "BDI", "value": "2026 強勢"},
            {"label": "台廠", "value": "裕民 / 慧洋"},
            {"label": "新船訂單", "value": "低"},
            {"label": "運價", "value": "支撐強"},
        ],
    },
    "鋼鐵": {
        "en": "Steel",
        "category": "傳產",
        "color": "#6b7280",
        "desc": "中鋼、東和鋼鐵、豐興等。2026 年中國限產 + 基建復甦。",
        "cagr": "—",
        "market_size": "—",
        "indicators": [
            {"label": "鋼價", "value": "回穩"},
            {"label": "中國產能", "value": "受限"},
            {"label": "台廠", "value": "中鋼 / 豐興"},
            {"label": "需求", "value": "基建 + 半導體廠"},
        ],
    },
    "水泥": {
        "en": "Cement",
        "category": "傳產",
        "color": "#78716c",
        "desc": "台泥、亞泥等。半導體廠建廠、公共建設帶動需求。",
        "cagr": "—",
        "market_size": "—",
        "indicators": [
            {"label": "需求", "value": "AI 廠房擴建"},
            {"label": "殖利率", "value": "4-6%"},
            {"label": "碳權", "value": "政策紅利"},
            {"label": "核心", "value": "台泥 / 亞泥"},
        ],
    },
    "營建/資產": {
        "en": "Construction & REIT",
        "category": "傳產",
        "color": "#92400e",
        "desc": "不動產開發 + 都更題材。2026 年央行鬆綁 + 重劃區熱絡。",
        "cagr": "—",
        "market_size": "—",
        "indicators": [
            {"label": "房市", "value": "價穩量縮"},
            {"label": "重劃區", "value": "台中 / 高雄"},
            {"label": "核心", "value": "興富發 / 華固"},
            {"label": "殖利率", "value": "4-7%"},
        ],
    },
    "食品/民生": {
        "en": "Food & Consumer",
        "category": "傳產",
        "color": "#ca8a04",
        "desc": "統一、佳格、卜蜂等。原物料回跌、毛利修復。",
        "cagr": "—",
        "market_size": "—",
        "indicators": [
            {"label": "原物料", "value": "回跌"},
            {"label": "毛利", "value": "修復中"},
            {"label": "龍頭", "value": "統一 / 佳格"},
            {"label": "防禦性", "value": "高"},
        ],
    },
    "綠能/儲能": {
        "en": "Green Energy / ESS",
        "category": "散熱 / 電源",
        "color": "#16a34a",
        "desc": "太陽能、風電、儲能系統。政策支持 + AI DC 綠電需求。",
        "cagr": "22%",
        "market_size": "—",
        "indicators": [
            {"label": "政策", "value": "淨零 2050"},
            {"label": "AI DC 綠電", "value": "全面轉向"},
            {"label": "台廠", "value": "台達 / 中興電"},
            {"label": "儲能", "value": "快速成長"},
        ],
    },
    "防疫/口罩": {
        "en": "Pandemic / PPE",
        "category": "事件驅動",
        "color": "#737373",
        "desc": "防疫相關類股。事件驅動性題材，波動大。",
        "cagr": "—",
        "market_size": "—",
        "indicators": [
            {"label": "性質", "value": "事件驅動"},
            {"label": "波動", "value": "高"},
            {"label": "核心", "value": "高端 / 寶齡"},
            {"label": "風險", "value": "題材過期"},
        ],
    },
    "宅經濟/遠距": {
        "en": "Stay-at-Home Economy",
        "category": "事件驅動",
        "color": "#a3a3a3",
        "desc": "電商、遠距辦公、線上娛樂。後疫情時代轉為結構性消費升級。",
        "cagr": "—",
        "market_size": "—",
        "indicators": [
            {"label": "結構性", "value": "電商滲透率"},
            {"label": "核心", "value": "網家 / 富邦媒"},
            {"label": "趨勢", "value": "O2O 整合"},
            {"label": "成長", "value": "個位數"},
        ],
    },

    # ═══════════════════════════════════════════
    #  2026 新增利基族群
    # ═══════════════════════════════════════════
    "碳化矽/SiC": {
        "en": "Silicon Carbide",
        "category": "第三代半導體",
        "color": "#f59e0b",
        "desc": "第三代半導體材料，耐高溫、高壓、高頻，電動車主逆變器 + AI 資料中心電源必備。"
                "從車用轉戰資料中心，漢磊、嘉晶、環球晶卡位。",
        "cagr": "35%",
        "market_size": "10B USD",
        "indicators": [
            {"label": "應用", "value": "EV / AI DC 電源"},
            {"label": "基板", "value": "6 吋 → 8 吋"},
            {"label": "台廠", "value": "漢磊 / 嘉晶"},
            {"label": "供需", "value": "2026 緊俏"},
        ],
    },
    "砷化鎵/GaAs": {
        "en": "Gallium Arsenide",
        "category": "第三代半導體",
        "color": "#eab308",
        "desc": "化合物半導體代工龍頭穩懋 + 磊晶供應鏈。受惠 CPO、衛星、WiFi 7 需求。",
        "cagr": "20%",
        "market_size": "6B USD",
        "indicators": [
            {"label": "應用", "value": "CPO / 衛星 / WiFi"},
            {"label": "龍頭", "value": "穩懋 全球 #1"},
            {"label": "客戶", "value": "Apple / CSP"},
            {"label": "技術", "value": "GaAs / InP"},
        ],
    },
    "矽晶圓": {
        "en": "Silicon Wafer",
        "category": "第三代半導體",
        "color": "#84cc16",
        "desc": "環球晶、中美晶、合晶三巨頭。2026 年先進製程對 12 吋矽晶圓需求強勁，SOI/SiC 基板為新戰場。",
        "cagr": "15%",
        "market_size": "15B USD",
        "indicators": [
            {"label": "尺寸", "value": "12 吋 / 8 吋 SiC"},
            {"label": "台廠全球", "value": "#3"},
            {"label": "新廠", "value": "環球晶美國擴產"},
            {"label": "長約", "value": "3-5 年"},
        ],
    },
    "石英元件": {
        "en": "Quartz Components",
        "category": "利基零組件",
        "color": "#14b8a6",
        "desc": "石英振盪器（OSC/TCXO）為 5G、AI 伺服器、衛星、車用的基礎時脈元件。晶技全球 TCXO 龍頭。",
        "cagr": "12%",
        "market_size": "3B USD",
        "indicators": [
            {"label": "應用", "value": "5G / AI / 衛星 / 車用"},
            {"label": "龍頭", "value": "晶技"},
            {"label": "規格", "value": "高頻低相噪"},
            {"label": "進入門檻", "value": "認證嚴"},
        ],
    },
    "工具機": {
        "en": "Machine Tools",
        "category": "利基零組件",
        "color": "#22c55e",
        "desc": "上銀線性滑軌 + 大銀微線性馬達 + 東台/亞崴工具機。受惠美中製造回流、機器人、半導體廠設備。",
        "cagr": "10%",
        "market_size": "8B USD",
        "indicators": [
            {"label": "下游", "value": "半導體 / 機器人 / EV"},
            {"label": "龍頭", "value": "上銀 / 程泰"},
            {"label": "驅動", "value": "製造回流 + 自動化"},
            {"label": "訂單", "value": "復甦中"},
        ],
    },
    "航太": {
        "en": "Aerospace",
        "category": "國防 / 資安",
        "color": "#b91c1c",
        "desc": "全球航空業復甦 + 國防預算倍增。漢翔、長榮航太、寶一卡位軍機 + 民航結構件。",
        "cagr": "18%",
        "market_size": "50B USD",
        "indicators": [
            {"label": "雙軌", "value": "軍用 + 民用"},
            {"label": "客戶", "value": "Boeing / 空中巴士"},
            {"label": "國防", "value": "F-16V / 無人機"},
            {"label": "台廠", "value": "漢翔 / 長榮航太"},
        ],
    },
    "氫能/燃料電池": {
        "en": "Hydrogen / Fuel Cell",
        "category": "散熱 / 電源",
        "color": "#06b6d4",
        "desc": "氫能列入國家淨零關鍵技術。燃料電池、氫能發電、氫能車三大方向。高力、中興電切入氫能系統。",
        "cagr": "50%",
        "market_size": "5B USD",
        "indicators": [
            {"label": "政策", "value": "淨零 2050"},
            {"label": "應用", "value": "發電 / 儲能 / 車用"},
            {"label": "台廠", "value": "高力 / 中興電"},
            {"label": "階段", "value": "示範 → 商轉"},
        ],
    },
    "造紙": {
        "en": "Paper & Packaging",
        "category": "傳產利基",
        "color": "#78350f",
        "desc": "工業用紙（電商包裝）+ 家用紙 + 再生紙漿。永豐餘、華紙、正隆為三強。ESG 再生紙需求結構性。",
        "cagr": "—",
        "market_size": "—",
        "indicators": [
            {"label": "驅動", "value": "電商包裝 + ESG"},
            {"label": "成本", "value": "木漿週期"},
            {"label": "龍頭", "value": "永豐餘 / 華紙"},
            {"label": "殖利率", "value": "4-6%"},
        ],
    },
    "輪胎/橡膠": {
        "en": "Tires & Rubber",
        "category": "傳產利基",
        "color": "#44403c",
        "desc": "正新、建大為全球輪胎中段，車用替換胎 + 電動車專用胎為成長亮點。原料天然橡膠價格敏感。",
        "cagr": "6%",
        "market_size": "—",
        "indicators": [
            {"label": "產品", "value": "替換胎 / EV 胎"},
            {"label": "市場", "value": "新興亞洲擴張"},
            {"label": "龍頭", "value": "正新 / 建大"},
            {"label": "原料", "value": "橡膠 / 合成"},
        ],
    },
    "寵物經濟": {
        "en": "Pet Economy",
        "category": "傳產利基",
        "color": "#f472b6",
        "desc": "少子化、高齡化帶動寵物經濟結構性成長。寵物食品、用品、醫療為三大區塊。",
        "cagr": "12%",
        "market_size": "—",
        "indicators": [
            {"label": "驅動", "value": "少子 + 高齡"},
            {"label": "ARPU", "value": "年增 8-10%"},
            {"label": "台廠", "value": "福壽 / 佳格"},
            {"label": "趨勢", "value": "鮮食 / 保健"},
        ],
    },
    "醫材": {
        "en": "Medical Devices",
        "category": "生技 / 醫療",
        "color": "#22d3ee",
        "desc": "血糖儀、呼吸照護、傷口敷料、血壓計等。雃博、泰博、邦特為代表。出口歐美 + 在地化優勢。",
        "cagr": "10%",
        "market_size": "—",
        "indicators": [
            {"label": "應用", "value": "居家 / 醫院"},
            {"label": "主力市場", "value": "歐美 + 東南亞"},
            {"label": "認證", "value": "FDA / CE"},
            {"label": "毛利", "value": "40-60%"},
        ],
    },
    "碳權/ESG": {
        "en": "Carbon Credit / ESG",
        "category": "政策驅動",
        "color": "#15803d",
        "desc": "2026 台灣碳費開徵 + 歐盟 CBAM 上路。高排碳業者透過減碳、綠電、碳權交易降低成本。",
        "cagr": "—",
        "market_size": "—",
        "indicators": [
            {"label": "政策", "value": "碳費 2026 / CBAM"},
            {"label": "受影響", "value": "鋼鐵 / 石化 / 水泥"},
            {"label": "解方", "value": "減碳 + 買碳權"},
            {"label": "碳交所", "value": "已營運"},
        ],
    },

    # ═══════════════════════════════════════════
    #  2026 Q2 補增：熱門新題材
    # ═══════════════════════════════════════════
    "海底電纜": {
        "en": "Submarine Cable",
        "category": "散熱 / 電源",
        "color": "#1e3a8a",
        "desc": "華新攜手丹麥 NKT 投資 180 億在高雄設海纜廠，2026 試產、2027 量產。離岸風電在地化硬指標，全球 AI DC 大陸海底互連需求噴發。",
        "cagr": "45%",
        "market_size": "15B USD",
        "indicators": [
            {"label": "量產時程", "value": "2027 年"},
            {"label": "台廠龍頭", "value": "華新（獨家）"},
            {"label": "驅動力", "value": "離岸風電 + AI DC"},
            {"label": "進入門檻", "value": "極高"},
        ],
    },
    "銅纜/銅加工": {
        "en": "Copper Cable",
        "category": "傳產",
        "color": "#b45309",
        "desc": "LME 銅價突破 $12,000 / 噸創歷史新高。華新、華榮、大亞、合機等電線大廠受惠，AI DC 電力互連銅需求急升。",
        "cagr": "18%",
        "market_size": "—",
        "indicators": [
            {"label": "LME 銅價", "value": "$12,000+ / 噸"},
            {"label": "驅動", "value": "AI DC / 電網升級"},
            {"label": "龍頭", "value": "華新 / 華榮 / 大亞"},
            {"label": "週期", "value": "3-5 年景氣向上"},
        ],
    },
    "減重新藥/GLP-1": {
        "en": "GLP-1 / Weight Loss",
        "category": "生技 / 醫療",
        "color": "#0891b2",
        "desc": "諾和諾德司美格魯肽、禮來 Tirzepatide 開創千億市場。2026 GLP-1 專利陸續到期，台廠 CDMO / 仿製藥 / 原料有機會分一杯羹。",
        "cagr": "30%",
        "market_size": "100B USD",
        "indicators": [
            {"label": "市場規模", "value": "2026 破千億 USD"},
            {"label": "台廠切入", "value": "仿製藥 / CDMO"},
            {"label": "專利到期", "value": "2026 起陸續"},
            {"label": "核心公司", "value": "合一 / 美時 / 保瑞"},
        ],
    },
    "固態電池": {
        "en": "Solid-State Battery",
        "category": "車用 / 機器人",
        "color": "#7c3aed",
        "desc": "2026 被視為固態電池「產業化」關鍵年，能量密度 +50%、安全性大幅提升。台廠電池模組、正負極材料、電源管理卡位。",
        "cagr": "80%",
        "market_size": "12B USD",
        "indicators": [
            {"label": "量產時程", "value": "2026-2028"},
            {"label": "應用", "value": "EV / 儲能 / 消費電子"},
            {"label": "台廠", "value": "新普 / 順達 / 美琪瑪"},
            {"label": "技術路線", "value": "多條並行"},
        ],
    },
    "遊戲股": {
        "en": "Gaming",
        "category": "消費電子",
        "color": "#e11d48",
        "desc": "鈊象博奕遊戲、智冠老牌、橘子線上遊戲。2026 年 AI 導入遊戲開發壓縮成本，出海東南亞市場成長。",
        "cagr": "8%",
        "market_size": "—",
        "indicators": [
            {"label": "類型", "value": "博奕 / MMO / 線上"},
            {"label": "龍頭", "value": "鈊象 / 智冠"},
            {"label": "趨勢", "value": "AI 開發 + 出海"},
            {"label": "殖利率", "value": "5-8%"},
        ],
    },
    "健身/運動用品": {
        "en": "Fitness & Sports",
        "category": "傳產",
        "color": "#65a30d",
        "desc": "喬山（健身器材全球前三）、巨大 / 美利達（自行車雙雄）。後疫情健身意識 + 高齡健康需求雙輪驅動。",
        "cagr": "6%",
        "market_size": "—",
        "indicators": [
            {"label": "核心", "value": "喬山 / 巨大 / 美利達"},
            {"label": "出口市場", "value": "歐美 + 中東"},
            {"label": "週期位置", "value": "庫存去化完畢"},
            {"label": "驅動", "value": "健康意識 + 高齡化"},
        ],
    },
    "軟體/SaaS": {
        "en": "Software / SaaS",
        "category": "AI / 半導體",
        "color": "#4f46e5",
        "desc": "AI 衝擊傳統 SaaS 按人計費模式，Salesforce、ServiceNow 股價受挫。台廠系統整合、資安、雲端卡位轉型。",
        "cagr": "12%",
        "market_size": "—",
        "indicators": [
            {"label": "轉型壓力", "value": "AI Agent 滲透"},
            {"label": "台廠", "value": "精誠 / 倍微 / 聚碩"},
            {"label": "機會", "value": "在地化整合"},
            {"label": "趨勢", "value": "定價模式重塑"},
        ],
    },
    "2奈米先進製程": {
        "en": "2nm Advanced Node",
        "category": "AI / 半導體",
        "color": "#dc2626",
        "desc": "台積電 2026 第 4 季開始量產 2nm，明年底月產能衝 10 萬片。世芯、創意、欣興、南電封測載板鏈全面受惠。",
        "cagr": "60%",
        "market_size": "50B USD",
        "indicators": [
            {"label": "量產", "value": "2026 Q4 起"},
            {"label": "月產能", "value": "2027 底 10 萬片"},
            {"label": "客戶", "value": "Apple / NVIDIA / AMD"},
            {"label": "台廠", "value": "TSMC 獨家"},
        ],
    },
    "稀土/關鍵金屬": {
        "en": "Rare Earth & Critical Metals",
        "category": "傳產",
        "color": "#a16207",
        "desc": "中美稀土貿易戰升級，AI / 電動車 / 國防需求推升釹鐵硼、鑭、釔等需求。台廠磁性元件、精密研磨受惠。",
        "cagr": "20%",
        "market_size": "—",
        "indicators": [
            {"label": "關鍵金屬", "value": "釹鐵硼 / 鑭 / 釔"},
            {"label": "應用", "value": "馬達 / 雷達 / 半導體"},
            {"label": "地緣", "value": "去中國化供應"},
            {"label": "台廠", "value": "泰銘 / 中砂"},
        ],
    },
    "銀髮/高齡經濟": {
        "en": "Silver Economy",
        "category": "生技 / 醫療",
        "color": "#db2777",
        "desc": "台灣 2025 進入超高齡社會，65 歲以上破 20%。長照、藥局連鎖、醫材、健康食品、旅遊全面受惠。",
        "cagr": "10%",
        "market_size": "—",
        "indicators": [
            {"label": "65+ 人口", "value": "20%+"},
            {"label": "長照預算", "value": "持續擴編"},
            {"label": "核心公司", "value": "大樹 / 杏一 / 葡萄王"},
            {"label": "結構性", "value": "不可逆"},
        ],
    },
    "電商/網購": {
        "en": "E-Commerce",
        "category": "消費電子",
        "color": "#0284c7",
        "desc": "富邦媒、網家、PChome。雙 11 / 618 年促帶動流量高峰，2026 物流自動化 + AI 推薦提升毛利。",
        "cagr": "8%",
        "market_size": "—",
        "indicators": [
            {"label": "龍頭", "value": "富邦媒 / 網家"},
            {"label": "毛利改善", "value": "AI 推薦"},
            {"label": "物流", "value": "自動化倉儲"},
            {"label": "週期", "value": "Q4 旺季"},
        ],
    },
    "影音串流/OTT": {
        "en": "OTT & Streaming",
        "category": "消費電子",
        "color": "#7c3aed",
        "desc": "Netflix、Disney+、LINE TV 台灣深耕。在地化內容 + 廣告訂閱混合模式興起。台廠代理商 / 直播平台受惠。",
        "cagr": "12%",
        "market_size": "—",
        "indicators": [
            {"label": "趨勢", "value": "廣告訂閱雙軌"},
            {"label": "代理", "value": "隆中 / 網家"},
            {"label": "直播", "value": "橘子 / 鑫科"},
            {"label": "競爭", "value": "平台整併"},
        ],
    },
    "折疊機/Apple 新機": {
        "en": "Foldable / Apple New Device",
        "category": "消費電子",
        "color": "#6b21a8",
        "desc": "蘋果 2026 H2 推摺疊 iPhone 與新款 iPad，台廠鉸鏈、OLED、鏡頭模組吃 big bite。",
        "cagr": "25%",
        "market_size": "—",
        "indicators": [
            {"label": "發表時程", "value": "2026 H2"},
            {"label": "關鍵零件", "value": "鉸鏈 / OLED"},
            {"label": "台廠", "value": "新日興 / 大立光 / 群光"},
            {"label": "ASP 提升", "value": "高於現有機型"},
        ],
    },
    "HBM 高頻寬記憶體": {
        "en": "HBM Memory",
        "category": "AI / 半導體",
        "color": "#b91c1c",
        "desc": "AI 伺服器單顆 GPU 配 6-8 顆 HBM。2026 HBM3E / HBM4 量產，三星、SK 海力士、美光壟斷產能。台廠封測 + 載板受惠。",
        "cagr": "50%",
        "market_size": "35B USD",
        "indicators": [
            {"label": "代際", "value": "HBM3E / HBM4"},
            {"label": "供給", "value": "極度吃緊"},
            {"label": "台廠卡位", "value": "測試 / 載板"},
            {"label": "ASP", "value": "年增 50%+"},
        ],
    },
    "量子電腦": {
        "en": "Quantum Computing",
        "category": "AI / 半導體",
        "color": "#312e81",
        "desc": "IBM、Google、Microsoft 推量子運算，2026 年 1000+ qubit 節點突破。台積電 / 日月光為超導量子晶片提供先進封裝。",
        "cagr": "100%+",
        "market_size": "5B USD",
        "indicators": [
            {"label": "節點", "value": "2026 破千 qubit"},
            {"label": "應用", "value": "加密 / 藥物 / AI"},
            {"label": "封裝需求", "value": "TSMC / ASE"},
            {"label": "階段", "value": "NISQ → 容錯"},
        ],
    },
    "AI 智慧醫療": {
        "en": "AI Healthcare",
        "category": "生技 / 醫療",
        "color": "#0f766e",
        "desc": "AI 影像診斷、精準醫療、新藥設計。FDA 核可 AI 醫材加速，台廠承業醫、杏一、聯詠（醫療影像）卡位。",
        "cagr": "35%",
        "market_size": "40B USD",
        "indicators": [
            {"label": "應用", "value": "影像 / 診斷 / 新藥"},
            {"label": "監管", "value": "FDA 加速核可"},
            {"label": "台廠", "value": "承業醫 / 合一"},
            {"label": "驅動", "value": "高齡 + AI 平價化"},
        ],
    },
    "新南向/東南亞產能": {
        "en": "New Southbound / ASEAN",
        "category": "政策驅動",
        "color": "#059669",
        "desc": "美中貿易戰與地緣政治推動製造業移出中國。紡織、自行車、PCB、電子代工加速越南 / 印度 / 印尼佈局。",
        "cagr": "20%",
        "market_size": "—",
        "indicators": [
            {"label": "主要地", "value": "越南 / 印度 / 印尼"},
            {"label": "產業", "value": "紡織 / 自行車 / PCB"},
            {"label": "政策", "value": "台灣新南向"},
            {"label": "期間", "value": "2024-2030"},
        ],
    },
    "氮化鎵/GaN": {
        "en": "Gallium Nitride",
        "category": "第三代半導體",
        "color": "#fb923c",
        "desc": "GaN 耐高壓、高功率、低損耗，適用 EV、5G、快充、AI 眼鏡。Wolfspeed 重整後台廠穩懋、力積電吃下轉單。",
        "cagr": "40%",
        "market_size": "6B USD",
        "indicators": [
            {"label": "應用", "value": "快充 / 5G / AI 眼鏡"},
            {"label": "台廠代工", "value": "力積電 / 穩懋"},
            {"label": "獨家 MOCVD", "value": "億豐（Google 供應）"},
            {"label": "2026 量產", "value": "產能倍增"},
        ],
    },
    "特用化學/光阻劑": {
        "en": "Specialty Chemicals",
        "category": "AI / 半導體",
        "color": "#be123c",
        "desc": "2nm 製程帶動 EUV 光阻、ArF 光阻需求。新應材、達興材料、勝一卡位半導體化學品。毛利高、認證週期長。",
        "cagr": "25%",
        "market_size": "8B USD",
        "indicators": [
            {"label": "關鍵材料", "value": "EUV 光阻 / 顯影"},
            {"label": "台廠", "value": "新應材 / 達興"},
            {"label": "毛利", "value": "40-60%"},
            {"label": "進入門檻", "value": "3-5 年認證"},
        ],
    },
    "充電樁/充電服務": {
        "en": "EV Charging",
        "category": "車用 / 機器人",
        "color": "#16a34a",
        "desc": "全球電動車滲透 35%，充電樁佈建加速。台達電全球 DC 快充龍頭、華城、中興電卡位國內充電站。",
        "cagr": "35%",
        "market_size": "25B USD",
        "indicators": [
            {"label": "全球需求", "value": "年增 35%+"},
            {"label": "台廠", "value": "台達電 #1"},
            {"label": "規格", "value": "DC 350kW 超快充"},
            {"label": "政策", "value": "美歐補貼"},
        ],
    },
    "生技 CDMO": {
        "en": "Biotech CDMO",
        "category": "生技 / 醫療",
        "color": "#0891b2",
        "desc": "全球 CDMO 市場突破 1,500 億美元。保瑞借殼收購海內外藥廠、台康生技擴建桃園廠。受益 GLP-1 委外製造。",
        "cagr": "15%",
        "market_size": "150B USD",
        "indicators": [
            {"label": "龍頭", "value": "保瑞（併購王）"},
            {"label": "GLP-1 委外", "value": "需求湧現"},
            {"label": "產能", "value": "2026 大擴"},
            {"label": "客戶", "value": "全球大藥廠"},
        ],
    },
    "水資源/環保": {
        "en": "Water & Environment",
        "category": "傳產",
        "color": "#0ea5e9",
        "desc": "半導體廠用水大戶 + 氣候變遷。國統、山林水水處理工程、再生水需求提升。政策面淨零 2050 加速落地。",
        "cagr": "8%",
        "market_size": "—",
        "indicators": [
            {"label": "驅動", "value": "缺水 + 半導體擴廠"},
            {"label": "台廠", "value": "國統 / 山林水"},
            {"label": "政策", "value": "淨零 + 再生水"},
            {"label": "毛利", "value": "政府標案高"},
        ],
    },
    "穿戴/智慧眼鏡": {
        "en": "Wearables / Smart Glasses",
        "category": "消費電子",
        "color": "#9333ea",
        "desc": "Meta Ray-Ban、Apple Vision Pro 帶動智慧眼鏡市場。2026 滲透率爆發，台廠鏡頭、SoC、鉸鏈受惠。",
        "cagr": "50%",
        "market_size": "10B USD",
        "indicators": [
            {"label": "核心產品", "value": "Meta / Apple / Google"},
            {"label": "量產", "value": "2026 大爆發"},
            {"label": "台廠", "value": "大立光 / 群光 / 聯發"},
            {"label": "技術", "value": "MicroLED / 光波導"},
        ],
    },
    "功率半導體 IC": {
        "en": "Power IC",
        "category": "AI / 半導體",
        "color": "#dc2626",
        "desc": "AI 伺服器、EV、快充均需高效率功率管理 IC。茂達、大中、矽力 KY 為代表。GaN / SiC 整合加速。",
        "cagr": "18%",
        "market_size": "30B USD",
        "indicators": [
            {"label": "應用", "value": "AI DC / EV / 快充"},
            {"label": "台廠", "value": "茂達 / 大中 / 矽力"},
            {"label": "整合", "value": "GaN / SiC"},
            {"label": "毛利", "value": "40%+"},
        ],
    },
    "AI 眼鏡 / Meta Ray-Ban": {
        "en": "AI Smart Glasses",
        "category": "消費電子",
        "color": "#c026d3",
        "desc": "Meta Ray-Ban 銷量超預期，Google Samsung Android XR 2026 上市。億豐 GaN MOCVD 獨家供應 Google，穩懋 RF 卡位。",
        "cagr": "80%+",
        "market_size": "8B USD",
        "indicators": [
            {"label": "領頭產品", "value": "Meta Ray-Ban"},
            {"label": "Android XR", "value": "2026 上市"},
            {"label": "獨家供應", "value": "億豐（Google GaN）"},
            {"label": "台廠 RF", "value": "穩懋"},
        ],
    },
    "Chiplet 小晶片": {
        "en": "Chiplet", "category": "封裝 / 測試", "color": "#f59e0b",
        "desc": "將大型 SoC 拆成多個小晶片（chiplet），以 UCIe 介面互連。突破摩爾定律瓶頸，AMD、Intel、Apple 全面採用。",
        "cagr": "55%", "market_size": "25B USD",
        "indicators": [{"label":"規格","value":"UCIe 介面"},{"label":"封裝","value":"CoWoS / SoIC"},{"label":"台廠","value":"TSMC / ASE"},{"label":"趨勢","value":"取代 SoC"}],
    },
    "DDR5/LPDDR5 記憶體": {
        "en": "DDR5 Memory", "category": "AI / 半導體", "color": "#b91c1c",
        "desc": "AI 伺服器、PC、手機全面升級 DDR5 / LPDDR5。2026 Q1 供應緊、價格大漲，南亞科、華邦電量產受惠。",
        "cagr": "30%", "market_size": "60B USD",
        "indicators": [{"label":"漲價","value":"2026 Q1 +20%"},{"label":"缺貨","value":"AI 需求湧入"},{"label":"台廠","value":"南亞科 / 華邦"},{"label":"規格","value":"DDR5-6400+"}],
    },
    "5G/6G 基地台": {
        "en": "5G/6G Base Station", "category": "光通訊 / 網通", "color": "#0d9488",
        "desc": "5G 滲透率接近飽和、6G 規格已定義。中磊、啟碁、智邦為 Open RAN 主力供應商。",
        "cagr": "15%", "market_size": "80B USD",
        "indicators": [{"label":"6G 時程","value":"2030 商用"},{"label":"架構","value":"Open RAN"},{"label":"台廠","value":"中磊 / 啟碁 / 智邦"},{"label":"驅動","value":"北美 + 日本需求"}],
    },
    "射頻 RF/PA": {
        "en": "RF / PA", "category": "光通訊 / 網通", "color": "#0891b2",
        "desc": "手機、WiFi、衛星需高頻功率放大器。穩懋、全新、宏捷科為 GaAs 代工三雄。",
        "cagr": "12%", "market_size": "25B USD",
        "indicators": [{"label":"應用","value":"手機 / WiFi / 衛星"},{"label":"代工三雄","value":"穩懋 / 全新 / 宏捷"},{"label":"規格","value":"GaAs / GaN HEMT"},{"label":"客戶","value":"Qualcomm / Skyworks"}],
    },
    "智慧家庭/Matter": {
        "en": "Smart Home / Matter", "category": "消費電子", "color": "#6366f1",
        "desc": "Matter 開放標準打破 Apple Home、Google Home、Alexa 生態隔閡。台廠網通廠加速 Matter 認證。",
        "cagr": "25%", "market_size": "30B USD",
        "indicators": [{"label":"標準","value":"Matter 1.3+"},{"label":"推動方","value":"CSA 聯盟"},{"label":"台廠","value":"友訊 / 啟碁 / 中磊"},{"label":"滲透","value":"2026 爆發期"}],
    },
    "智慧電錶/AMI": {
        "en": "Smart Meter / AMI", "category": "散熱 / 電源", "color": "#eab308",
        "desc": "台電智慧電錶 300 萬戶汰換計畫。中興電、士電、華城為標案主要得主。",
        "cagr": "20%", "market_size": "—",
        "indicators": [{"label":"台電標案","value":"300 萬戶"},{"label":"週期","value":"2025-2028"},{"label":"台廠","value":"中興電 / 士電"},{"label":"整合","value":"5G NB-IoT"}],
    },
    "美國製造回流/晶片法案": {
        "en": "CHIPS Act", "category": "政策驅動", "color": "#1e40af",
        "desc": "美國 CHIPS Act 390 億補貼吸引台廠赴美設廠。台積電亞利桑那、環球晶德州、鴻海威斯康辛陸續量產。",
        "cagr": "—", "market_size": "—",
        "indicators": [{"label":"補貼規模","value":"390 億 USD"},{"label":"台廠赴美","value":"TSMC / 環球晶"},{"label":"地緣","value":"中美脫鉤"},{"label":"關稅","value":"川普 2.0 施壓"}],
    },
    "印度產能/印度概念": {
        "en": "India Manufacturing", "category": "政策驅動", "color": "#fb923c",
        "desc": "Apple 分散產能、PLI 補貼吸引台廠赴印。鴻海、廣達、緯創、和碩印度廠陸續開出。",
        "cagr": "30%", "market_size": "—",
        "indicators": [{"label":"驅動","value":"去中國化 / PLI"},{"label":"台廠","value":"鴻海 / 廣達 / 緯創"},{"label":"產品","value":"iPhone / AI 伺服器"},{"label":"時程","value":"2026-2028 擴廠"}],
    },
    "鋰電池材料": {
        "en": "Lithium Battery Materials", "category": "車用 / 機器人", "color": "#84cc16",
        "desc": "EV 與儲能雙引擎推升電池材料需求。美琪瑪、康普正極、負極、電解液材料。",
        "cagr": "22%", "market_size": "30B USD",
        "indicators": [{"label":"應用","value":"EV / 儲能"},{"label":"台廠","value":"美琪瑪 / 康普"},{"label":"技術","value":"磷酸鐵鋰 / 三元"},{"label":"週期","value":"庫存去化完"}],
    },
    "儲能系統/BESS": {
        "en": "Battery Energy Storage", "category": "散熱 / 電源", "color": "#10b981",
        "desc": "台電儲能 2026 目標 3 GW、全球 BESS 年增 40%。台達電、華城為 PCS 主力，森崴能源整合案場。",
        "cagr": "40%", "market_size": "50B USD",
        "indicators": [{"label":"台電目標","value":"2026 3GW"},{"label":"PCS 龍頭","value":"台達 / 華城"},{"label":"案場","value":"森崴能源"},{"label":"驅動","value":"AI DC + 再生能源"}],
    },
    "PC/電競品牌": {
        "en": "PC / Gaming Brand", "category": "消費電子", "color": "#64748b",
        "desc": "華碩、宏碁 PC 品牌 + 技嘉、微星電競。AI PC 換機潮 2026 啟動。",
        "cagr": "10%", "market_size": "300B USD",
        "indicators": [{"label":"AI PC","value":"滲透率衝高"},{"label":"台廠","value":"華碩 / 宏碁 / 技嘉"},{"label":"週期","value":"Win10 EOL 換機"},{"label":"通路","value":"全球前五"}],
    },
    "伺服器準系統": {
        "en": "Server Barebone", "category": "AI / 半導體", "color": "#f97316",
        "desc": "AI 伺服器準系統組裝。緯穎 CSP 直營、廣達 NVIDIA 獨家、鴻海規模第一。",
        "cagr": "40%", "market_size": "150B USD",
        "indicators": [{"label":"CSP 直營","value":"緯穎"},{"label":"NVIDIA GB200","value":"廣達 / 鴻海"},{"label":"台廠代工","value":">90%"},{"label":"毛利","value":"低但量大"}],
    },
    "特殊氣體/半導體化學品": {
        "en": "Specialty Gas", "category": "AI / 半導體", "color": "#a855f7",
        "desc": "半導體製程必需 NF3、WF6、SiH4 等特殊氣體。崇越、雙鍵、勝一為代理與生產。",
        "cagr": "18%", "market_size": "12B USD",
        "indicators": [{"label":"關鍵氣體","value":"NF3 / WF6 / SiH4"},{"label":"台廠","value":"崇越 / 雙鍵"},{"label":"驅動","value":"先進製程 + 擴產"},{"label":"毛利","value":"40%+"}],
    },
    "晶圓代工成熟製程": {
        "en": "Mature Node Foundry", "category": "AI / 半導體", "color": "#475569",
        "desc": "聯電、世界先進、力積電。車用 / 工控 / 消費電子 IC 需求回溫，2026 稼動率回升。",
        "cagr": "8%", "market_size": "60B USD",
        "indicators": [{"label":"節點","value":"28nm / 40nm / 55nm"},{"label":"應用","value":"車用 / IoT / 顯示"},{"label":"稼動率","value":"2026 回升"},{"label":"台廠","value":"聯電 / 世界 / 力積"}],
    },
    "NAND Flash/SSD 控制": {
        "en": "NAND Flash / SSD", "category": "AI / 半導體", "color": "#e11d48",
        "desc": "QLC NAND 滲透、AI 伺服器 SSD 容量翻倍。群聯 aiDAPTIV+ 將 SSD 模擬為 DRAM。",
        "cagr": "25%", "market_size": "70B USD",
        "indicators": [{"label":"技術","value":"QLC / PLC NAND"},{"label":"控制晶片","value":"群聯"},{"label":"aiDAPTIV+","value":"AI DC 採用"},{"label":"容量","value":"翻倍成長"}],
    },
    "安全監控/影像監控": {
        "en": "Video Surveillance", "category": "國防 / 資安", "color": "#991b1b",
        "desc": "AI 影像辨識加速取代傳統 DVR。晶睿、奇偶卡位智慧城市、交通、邊境安控。",
        "cagr": "15%", "market_size": "30B USD",
        "indicators": [{"label":"趨勢","value":"AI 邊緣運算"},{"label":"台廠","value":"晶睿 / 奇偶"},{"label":"應用","value":"智慧城市 / 交通"},{"label":"去中國化","value":"海康禁令受惠"}],
    },
    "高階 PCB/HDI": {
        "en": "HDI / High-end PCB", "category": "基板 / PCB", "color": "#dc2626",
        "desc": "HDI 任意層互連 + 超薄 Any-layer。手機主板、AI 伺服器訊號層高階化。",
        "cagr": "15%", "market_size": "30B USD",
        "indicators": [{"label":"應用","value":"手機 / AI DC"},{"label":"台廠","value":"健鼎 / 華通"},{"label":"技術","value":"Any-layer / mSAP"},{"label":"漲價","value":"2026 Q1 10-40%"}],
    },
    "Flexible PCB/軟板": {
        "en": "Flexible PCB", "category": "基板 / PCB", "color": "#f43f5e",
        "desc": "軟板用於手機、穿戴、摺疊機、車用。健鼎、嘉聯益、台郡受惠 Apple 新機。",
        "cagr": "12%", "market_size": "18B USD",
        "indicators": [{"label":"應用","value":"手機 / 摺疊 / 穿戴"},{"label":"台廠","value":"嘉聯益 / 台郡 / 健鼎"},{"label":"客戶","value":"Apple / Samsung"},{"label":"驅動","value":"2026 折疊機"}],
    },
    "紡織/機能布": {
        "en": "Functional Textile", "category": "傳產利基", "color": "#1d4ed8",
        "desc": "儒鴻、聚陽接歐美大廠運動機能布訂單。品牌客戶 Nike、Lululemon、Under Armour。東南亞產能切換。",
        "cagr": "8%", "market_size": "—",
        "indicators": [{"label":"客戶","value":"Nike / Lululemon"},{"label":"台廠","value":"儒鴻 / 聚陽"},{"label":"產能","value":"越南為主"},{"label":"毛利","value":"25-30%"}],
    },
    "自行車零件": {
        "en": "Bicycle Components", "category": "傳產利基", "color": "#166534",
        "desc": "巨大、美利達雙雄。電動自行車滲透率提升，高階休閒車需求回升。",
        "cagr": "6%", "market_size": "—",
        "indicators": [{"label":"龍頭","value":"巨大 / 美利達"},{"label":"趨勢","value":"電動自行車"},{"label":"週期","value":"庫存去化完"},{"label":"市場","value":"歐美 + 日本"}],
    },
    "螺絲/螺帽/緊固件": {
        "en": "Fasteners", "category": "傳產利基", "color": "#78716c",
        "desc": "台灣世界第三大螺絲出口國。亞德客、春雨供應汽車、航太、家具。",
        "cagr": "5%", "market_size": "—",
        "indicators": [{"label":"全球排名","value":"#3 出口"},{"label":"應用","value":"汽車 / 航太"},{"label":"台廠","value":"亞德客 / 春雨"},{"label":"客群","value":"全球 B2B"}],
    },
    "手工具/電動工具": {
        "en": "Hand & Power Tools", "category": "傳產利基", "color": "#57534e",
        "desc": "台灣手工具產業世界頂尖。美國 Home Depot、Lowe's 主要供應商。",
        "cagr": "6%", "market_size": "—",
        "indicators": [{"label":"主要市場","value":"美國"},{"label":"渠道","value":"Home Depot"},{"label":"台廠","value":"亞德客 / 鼎炫"},{"label":"競爭","value":"品質 vs 中國"}],
    },
    "軸承/精密機構": {
        "en": "Bearings", "category": "利基零組件", "color": "#6b7280",
        "desc": "上銀滾珠螺桿、川湖滑軌、大銀微線性馬達。半導體廠 / 機器人 / 伺服器機櫃必備。",
        "cagr": "12%", "market_size": "—",
        "indicators": [{"label":"應用","value":"半導體 / 機器人"},{"label":"台廠","value":"上銀 / 川湖"},{"label":"關鍵","value":"精密滑軌"},{"label":"驅動","value":"自動化 + AI DC"}],
    },
    "光學鏡片/鏡頭": {
        "en": "Optical Lens", "category": "消費電子", "color": "#0369a1",
        "desc": "大立光全球手機鏡頭龍頭。車用、AR/VR、安控鏡頭快速成長。",
        "cagr": "10%", "market_size": "15B USD",
        "indicators": [{"label":"龍頭","value":"大立光 全球 #1"},{"label":"應用","value":"手機 / 車用 / AR"},{"label":"利潤","value":"極高"},{"label":"競爭","value":"Samsung 子公司"}],
    },
    "光學薄膜": {
        "en": "Optical Film", "category": "面板 / 光電", "color": "#7e22ce",
        "desc": "面板背光、偏光、擴散膜。和鑫、明基材台廠為日系對手。",
        "cagr": "5%", "market_size": "—",
        "indicators": [{"label":"應用","value":"面板 / LED"},{"label":"台廠","value":"和鑫 / 明基材"},{"label":"對手","value":"日本日東電工"},{"label":"毛利","value":"15-25%"}],
    },
    "汽車零件/售後": {
        "en": "Auto Parts", "category": "車用 / 機器人", "color": "#854d0e",
        "desc": "東陽、和大、為升。美規保修件 + EV 輕量化零件雙主軸。全球 AM 市場穩定成長。",
        "cagr": "8%", "market_size": "—",
        "indicators": [{"label":"主軸","value":"AM 保修 + EV"},{"label":"台廠","value":"東陽 / 和大 / 為升"},{"label":"客群","value":"美國 + 歐洲"},{"label":"毛利","value":"20-30%"}],
    },
    "塑膠射出/模具": {
        "en": "Plastic Injection", "category": "傳產利基", "color": "#404040",
        "desc": "3C 機殼、醫材零件、車用內裝塑膠射出。利勤、亞聚等本土廠。",
        "cagr": "—", "market_size": "—",
        "indicators": [{"label":"應用","value":"3C / 醫材 / 車用"},{"label":"台廠","value":"利勤 / 亞聚"},{"label":"趨勢","value":"自動化+環保料"},{"label":"客群","value":"OEM / ODM"}],
    },
    "齒輪/減速機": {
        "en": "Gears & Reducers", "category": "利基零組件", "color": "#047857",
        "desc": "工業機器人、工具機核心零件。上銀諧波減速機切入人形機器人供應鏈。",
        "cagr": "15%", "market_size": "—",
        "indicators": [{"label":"應用","value":"機器人 / 工具機"},{"label":"龍頭","value":"上銀"},{"label":"新機會","value":"人形機器人"},{"label":"精度","value":"高端市場"}],
    },
    "金屬粉末/3D 列印": {
        "en": "Metal Powder / 3D Printing", "category": "利基零組件", "color": "#7c2d12",
        "desc": "3D 列印切入航太、醫材、汽車零件。台灣金屬粉末產業具精密加工優勢。",
        "cagr": "20%", "market_size": "20B USD",
        "indicators": [{"label":"應用","value":"航太 / 醫材"},{"label":"台廠","value":"中砂 / 波力-KY"},{"label":"技術","value":"SLM / EBM"},{"label":"成長","value":"年 20%+"}],
    },
    "真空設備": {
        "en": "Vacuum Equipment", "category": "封裝 / 測試", "color": "#1e3a8a",
        "desc": "半導體、面板、LED 廠關鍵真空設備。日揚、漢唐為本土主要供應商。",
        "cagr": "10%", "market_size": "—",
        "indicators": [{"label":"應用","value":"半導體 / 面板"},{"label":"台廠","value":"日揚 / 漢唐"},{"label":"對手","value":"日系廠"},{"label":"週期","value":"擴廠同步"}],
    },
    "碳纖維/輕量材料": {
        "en": "Carbon Fiber", "category": "傳產利基", "color": "#374151",
        "desc": "航太、自行車、EV 車身輕量化。台灣少數碳纖維製造商 + 複材加工廠。",
        "cagr": "12%", "market_size": "5B USD",
        "indicators": [{"label":"應用","value":"航太 / 自行車 / EV"},{"label":"台廠","value":"華紙 / 巨大"},{"label":"趨勢","value":"EV 輕量化"},{"label":"門檻","value":"技術高"}],
    },
    "閥門管材": {
        "en": "Valves & Pipes", "category": "傳產", "color": "#713f12",
        "desc": "半導體廠、石化、水處理用精密閥門管材。華榮、國統為代表。",
        "cagr": "8%", "market_size": "—",
        "indicators": [{"label":"應用","value":"半導體 / 水處理"},{"label":"台廠","value":"華榮 / 國統"},{"label":"驅動","value":"TSMC 擴廠"},{"label":"毛利","value":"20-30%"}],
    },
    "熱交換器/散熱器": {
        "en": "Heat Exchanger", "category": "散熱 / 電源", "color": "#0891b2",
        "desc": "AI 伺服器液冷 CDU、冷板、Heat Pipe。奇鋐、雙鴻、健策、高力為液冷五虎。",
        "cagr": "55%", "market_size": "8B USD",
        "indicators": [{"label":"產品","value":"CDU / 冷板"},{"label":"液冷五虎","value":"奇鋐 / 雙鴻 / 健策"},{"label":"世代","value":"GB200+"},{"label":"BOM 提升","value":"x5-8"}],
    },
    "細胞治療": {
        "en": "Cell Therapy", "category": "生技 / 醫療", "color": "#be185d",
        "desc": "CAR-T 細胞療法 + 免疫細胞治療。台廠合一、浩鼎切入實體腫瘤治療。",
        "cagr": "30%", "market_size": "10B USD",
        "indicators": [{"label":"技術","value":"CAR-T / NK"},{"label":"台廠","value":"合一 / 浩鼎"},{"label":"適應症","value":"血癌 / 實體瘤"},{"label":"階段","value":"臨床 II/III"}],
    },
    "疫苗/抗體新藥": {
        "en": "Vaccines & Antibodies", "category": "生技 / 醫療", "color": "#be123c",
        "desc": "mRNA、腺病毒、蛋白次單位疫苗。高端、國光為主力廠，台康 CDMO 承接全球訂單。",
        "cagr": "15%", "market_size": "60B USD",
        "indicators": [{"label":"技術","value":"mRNA / 蛋白質"},{"label":"台廠","value":"高端 / 國光"},{"label":"CDMO","value":"台康生技"},{"label":"出海","value":"東南亞"}],
    },
    "精準診斷/體外診斷": {
        "en": "IVD / Diagnostics", "category": "生技 / 醫療", "color": "#c2410c",
        "desc": "血糖、癌症、基因檢測 IVD 市場。泰博全球血糖儀龍頭之一，明基醫拓展雲端診斷。",
        "cagr": "12%", "market_size": "90B USD",
        "indicators": [{"label":"應用","value":"血糖 / 癌篩 / 基因"},{"label":"台廠","value":"泰博 / 明基醫"},{"label":"毛利","value":"40-60%"},{"label":"認證","value":"FDA / CE"}],
    },
    "醫美/雷射": {
        "en": "Medical Aesthetic", "category": "生技 / 醫療", "color": "#db2777",
        "desc": "美白、除皺、減脂市場。晶碩隱形眼鏡、邦特醫材。高毛利、可重複消費。",
        "cagr": "12%", "market_size": "—",
        "indicators": [{"label":"台廠","value":"晶碩 / 邦特"},{"label":"毛利","value":"40%+"},{"label":"回購率","value":"高"},{"label":"驅動","value":"消費升級"}],
    },
    "手術機器人/智慧醫療器材": {
        "en": "Surgical Robot", "category": "生技 / 醫療", "color": "#9d174d",
        "desc": "Intuitive da Vinci 系統 + 國產骨科手術機器人。台廠在精密機構、影像 AI 切入。",
        "cagr": "20%", "market_size": "12B USD",
        "indicators": [{"label":"應用","value":"外科 / 骨科"},{"label":"台廠","value":"上銀 / 承業醫"},{"label":"精密零件","value":"滑軌 / 減速機"},{"label":"市場","value":"歐美日湧現"}],
    },
    "保健食品/機能食品": {
        "en": "Health Supplement", "category": "傳產", "color": "#15803d",
        "desc": "葡萄王靈芝、大江代工、卜蜂雞精。台灣銀髮化 + 健康意識推升。",
        "cagr": "10%", "market_size": "—",
        "indicators": [{"label":"龍頭","value":"葡萄王 / 大江"},{"label":"驅動","value":"高齡化"},{"label":"通路","value":"直銷 / 電商"},{"label":"毛利","value":"30-40%"}],
    },
    "農業科技/植物工廠": {
        "en": "AgriTech", "category": "傳產", "color": "#65a30d",
        "desc": "精緻農業、LED 植物工廠、智慧養殖。卜蜂、大成傳統農業+科技結合。",
        "cagr": "15%", "market_size": "—",
        "indicators": [{"label":"方向","value":"植物工廠 / 智慧養殖"},{"label":"台廠","value":"卜蜂 / 大成"},{"label":"政策","value":"精緻農業"},{"label":"出口","value":"日本 / 東南亞"}],
    },
    "旅遊/廉航/郵輪": {
        "en": "Travel / Airlines", "category": "傳產", "color": "#0284c7",
        "desc": "後疫情國際旅遊全面復甦。長榮航、華航機隊擴編、雄獅、山富旅行社回溫。",
        "cagr": "12%", "market_size": "—",
        "indicators": [{"label":"復甦度","value":"疫前 90%+"},{"label":"台廠","value":"雄獅 / 長榮航"},{"label":"機隊","value":"擴編"},{"label":"客單價","value":"提升"}],
    },
    "文創/IP 內容": {
        "en": "Creative Content", "category": "消費電子", "color": "#a21caf",
        "desc": "遊戲、影劇、動漫 IP 授權。橘子、智冠、鑫科經營 IP 週邊與授權。",
        "cagr": "10%", "market_size": "—",
        "indicators": [{"label":"類型","value":"遊戲 IP / 影劇"},{"label":"台廠","value":"橘子 / 智冠"},{"label":"出海","value":"東南亞 / 日本"},{"label":"商業模式","value":"授權 + 週邊"}],
    },
    "植物肉/替代蛋白": {
        "en": "Alternative Protein", "category": "傳產", "color": "#84cc16",
        "desc": "Impossible、Beyond Meat 帶動，台灣統一、卜蜂、大成投入替代蛋白研發。",
        "cagr": "20%", "market_size": "15B USD",
        "indicators": [{"label":"產品","value":"植物肉 / 培植肉"},{"label":"台廠","value":"統一 / 卜蜂"},{"label":"驅動","value":"ESG + 健康"},{"label":"挑戰","value":"消費者接受"}],
    },
    "智慧城市/V2X": {
        "en": "Smart City / V2X", "category": "政策驅動", "color": "#0891b2",
        "desc": "V2X 車聯網、智慧路燈、智慧電錶、AI 影像交通。台廠網通 + 重電雙線佈局。",
        "cagr": "20%", "market_size": "200B USD",
        "indicators": [{"label":"應用","value":"V2X / 路燈 / 監控"},{"label":"台廠","value":"中興電 / 啟碁"},{"label":"政策","value":"智慧城市建設"},{"label":"5G NR","value":"全面部署"}],
    },
    "川普概念/關稅戰": {
        "en": "Trump / Tariff", "category": "政策驅動", "color": "#7c2d12",
        "desc": "川普 2.0 預料對中國課 60% 關稅、對全球 10-20%。台灣供應鏈面臨重組。",
        "cagr": "—", "market_size": "—",
        "indicators": [{"label":"中國關稅","value":"60%"},{"label":"全球關稅","value":"10-20%"},{"label":"供應鏈","value":"美國製造回流"},{"label":"台廠","value":"大者恆大"}],
    },
    "日圓貶值受惠/台日合作": {
        "en": "JPY / Taiwan-Japan", "category": "政策驅動", "color": "#dc2626",
        "desc": "日圓持續走弱，台積電熊本、巨大日本市場、出口至日本廠商受惠。",
        "cagr": "—", "market_size": "—",
        "indicators": [{"label":"匯率","value":"JPY 持續貶值"},{"label":"台廠","value":"TSMC 熊本"},{"label":"台日合作","value":"Rapidus / 東電"},{"label":"進口","value":"原物料成本降"}],
    },
    "重建/災後/基礎建設": {
        "en": "Reconstruction", "category": "傳產", "color": "#6b7280",
        "desc": "台灣半導體擴廠 + 政府重大公建。台泥、中鋼、營建股受惠。",
        "cagr": "8%", "market_size": "—",
        "indicators": [{"label":"驅動","value":"TSMC 擴廠 + 公建"},{"label":"台廠","value":"台泥 / 中鋼 / 興富發"},{"label":"週期","value":"5-10 年"},{"label":"預算","value":"千億級"}],
    },
    "龍年受惠/文創遊戲": {
        "en": "Year of Dragon", "category": "事件驅動", "color": "#b45309",
        "desc": "華人農曆新年 + 遊戲節日版本 + 餐飲旺季。事件性題材，波動大。",
        "cagr": "—", "market_size": "—",
        "indicators": [{"label":"類型","value":"事件驅動"},{"label":"受惠","value":"遊戲 / 餐飲 / 旅遊"},{"label":"期間","value":"春節前後"},{"label":"風險","value":"題材過期"}],
    },

    # ═══════════════════════════════════════════
    #  2026 Q2 第七批新增題材
    # ═══════════════════════════════════════════
    "電子通路": {
        "en": "Electronics Distribution", "category": "電子通路 / 服務", "color": "#4338ca",
        "desc": "電子零件通路商，大聯大、文曄、聯強為三大龍頭。扮演 IC 設計廠與系統廠之間的關鍵角色，AI 元件短缺時價值大增。",
        "cagr": "8%", "market_size": "50B USD",
        "indicators": [{"label":"龍頭","value":"大聯大 / 文曄"},{"label":"毛利","value":"4-6%"},{"label":"AI 受益","value":"高階元件配額"},{"label":"殖利率","value":"5-8%"}],
    },
    "資訊服務/IT服務": {
        "en": "IT Services", "category": "電子通路 / 服務", "color": "#6366f1",
        "desc": "企業 IT 顧問、系統整合、委外服務。精誠、敦陽科、凌群為代表。數位轉型、AI 導入服務需求強。",
        "cagr": "12%", "market_size": "30B USD",
        "indicators": [{"label":"龍頭","value":"精誠 / 敦陽科"},{"label":"驅動","value":"企業數位轉型"},{"label":"AI 服務","value":"快速成長"},{"label":"毛利","value":"20-30%"}],
    },
    "雲端服務/SaaS": {
        "en": "Cloud / SaaS", "category": "雲端 / 軟體", "color": "#7c3aed",
        "desc": "軟體即服務、雲端平台、資料中心代管。91APP、綠界、LINEPAY 等新興雲端服務商快速成長。",
        "cagr": "25%", "market_size": "20B USD",
        "indicators": [{"label":"龍頭","value":"91APP / 綠界"},{"label":"毛利","value":"60-80%"},{"label":"商業模式","value":"訂閱"},{"label":"趨勢","value":"AI SaaS"}],
    },
    "工業電腦/IPC": {
        "en": "Industrial Computer", "category": "AI / 半導體", "color": "#0284c7",
        "desc": "研華、樺漢為全球 IPC 雙雄。AI 邊緣運算、智慧工廠、車聯網、醫療 IPC 為主要成長動能。",
        "cagr": "15%", "market_size": "12B USD",
        "indicators": [{"label":"龍頭","value":"研華 / 樺漢"},{"label":"應用","value":"AIoT / 工廠"},{"label":"毛利","value":"30-40%"},{"label":"全球市佔","value":"#1"}],
    },
    "製鞋/運動鞋代工": {
        "en": "Footwear OEM", "category": "運動 / 休閒", "color": "#be185d",
        "desc": "寶成、豐泰為 Nike、Adidas 全球最大代工廠。桂盟為全球自行車鏈條龍頭，鈺齊切入功能性鞋類。",
        "cagr": "6%", "market_size": "40B USD",
        "indicators": [{"label":"龍頭","value":"寶成 / 豐泰"},{"label":"客戶","value":"Nike / Adidas"},{"label":"產地","value":"越南 / 印尼"},{"label":"毛利","value":"15-20%"}],
    },
    "光通訊細分": {
        "en": "Optical Detail", "category": "光通訊 / 網通", "color": "#0891b2",
        "desc": "光通訊上下游細分鏈，包含光電裝置、光學模組、光收發器相關廠商，為 CPO 之外的傳統光通訊補充。",
        "cagr": "15%", "market_size": "8B USD",
        "indicators": [{"label":"應用","value":"10G-400G"},{"label":"台廠","value":"光環 / 璟德"},{"label":"客戶","value":"網通廠商"},{"label":"毛利","value":"20-30%"}],
    },
    "燃氣/天然氣": {
        "en": "Natural Gas", "category": "傳產", "color": "#d97706",
        "desc": "天然氣公用事業，政策價格穩定、高殖利率。大台北、欣天然、新海等區域燃氣公司為主。",
        "cagr": "5%", "market_size": "—",
        "indicators": [{"label":"龍頭","value":"大台北 / 欣天然"},{"label":"殖利率","value":"4-6%"},{"label":"管制","value":"政府訂價"},{"label":"防禦性","value":"高"}],
    },
    "廢棄物處理/環保": {
        "en": "Waste Treatment", "category": "綠能 / 環保", "color": "#059669",
        "desc": "工業廢棄物處理、垃圾焚化、環保工程。日友、可寧衛為龍頭，ESG 趨勢下結構性成長。",
        "cagr": "15%", "market_size": "8B USD",
        "indicators": [{"label":"龍頭","value":"日友 / 可寧衛"},{"label":"毛利","value":"30-40%"},{"label":"驅動","value":"ESG 法規"},{"label":"殖利率","value":"3-5%"}],
    },
    "連鎖零售/超商": {
        "en": "Retail Chain", "category": "傳產", "color": "#ea580c",
        "desc": "統一超、全家、寶雅為主要連鎖零售龍頭。民生必需消費、防禦性強，殖利率穩定。",
        "cagr": "6%", "market_size": "—",
        "indicators": [{"label":"龍頭","value":"統一超 / 全家"},{"label":"店數","value":"持續擴張"},{"label":"防禦性","value":"高"},{"label":"殖利率","value":"3-5%"}],
    },
    "貿易百貨/消費": {
        "en": "Trade & Retail", "category": "傳產", "color": "#c2410c",
        "desc": "遠百、三商、特力等百貨零售族群。受消費性支出與觀光回溫雙重影響。",
        "cagr": "5%", "market_size": "—",
        "indicators": [{"label":"龍頭","value":"遠百 / 三商"},{"label":"景氣敏感","value":"中"},{"label":"轉型","value":"數位通路"},{"label":"殖利率","value":"3-5%"}],
    },
    "玻璃陶瓷/衛浴": {
        "en": "Glass & Ceramics", "category": "建材 / 居家", "color": "#a16207",
        "desc": "台玻、冠軍、和成、凱撒衛等傳統玻璃陶瓷、衛浴設備廠。房市 + 建材需求雙重影響。",
        "cagr": "4%", "market_size": "—",
        "indicators": [{"label":"龍頭","value":"台玻 / 和成"},{"label":"下游","value":"建材 / 衛浴"},{"label":"殖利率","value":"3-5%"},{"label":"景氣","value":"隨建案"}],
    },
    "橡膠/輪胎原料": {
        "en": "Rubber Material", "category": "傳產利基", "color": "#44403c",
        "desc": "南帝、台橡、鑫永銓等特用橡膠、SBR、BR 原料廠。電動車專用胎 + 輸送帶 + 工業橡膠需求。",
        "cagr": "6%", "market_size": "—",
        "indicators": [{"label":"產品","value":"SBR / BR / 合成橡膠"},{"label":"下游","value":"輪胎 / 輸送帶"},{"label":"台廠","value":"南帝 / 台橡"},{"label":"週期","value":"油價連動"}],
    },
    "化工/染料/特化": {
        "en": "Chemicals & Dyes", "category": "化工 / 特化", "color": "#9a3412",
        "desc": "長興、興農、台肥、中碳等化工基礎族群。電子級化學品、農藥、肥料、碳材料全面布局。",
        "cagr": "6%", "market_size": "—",
        "indicators": [{"label":"龍頭","value":"長興 / 中碳"},{"label":"分支","value":"染料 / 農藥 / 特化"},{"label":"毛利","value":"15-25%"},{"label":"景氣","value":"原油敏感"}],
    },
    "精密機械/自動化": {
        "en": "Precision Machinery", "category": "利基零組件", "color": "#14b8a6",
        "desc": "精密機械零組件、自動化設備、工業機械。受惠美中製造回流、機器人、半導體廠設備擴產。",
        "cagr": "10%", "market_size": "15B USD",
        "indicators": [{"label":"下游","value":"半導體 / 機器人"},{"label":"驅動","value":"自動化 + 回流"},{"label":"台廠","value":"全球傳動 / 富田"},{"label":"毛利","value":"20-30%"}],
    },
    "植栽/有機/飼料": {
        "en": "Agriculture & Feed", "category": "傳產", "color": "#16a34a",
        "desc": "飼料、肥料、農業生技族群。卜蜂、大成飼料雙雄，台肥肥料，興農農藥。",
        "cagr": "5%", "market_size": "—",
        "indicators": [{"label":"龍頭","value":"卜蜂 / 大成 / 台肥"},{"label":"下游","value":"畜牧 / 農業"},{"label":"殖利率","value":"3-5%"},{"label":"景氣","value":"糧食循環"}],
    },
    "文化傳媒/出版": {
        "en": "Media & Publishing", "category": "傳媒 / 文創", "color": "#a21caf",
        "desc": "電視、廣播、出版、娛樂內容。中視、台視、影一等，受數位轉型、串流衝擊。",
        "cagr": "3%", "market_size": "—",
        "indicators": [{"label":"媒體","value":"電視 / 平面"},{"label":"轉型","value":"數位 / OTT"},{"label":"毛利","value":"變動大"},{"label":"台廠","value":"中視 / 霹靂"}],
    },
    "原料藥/化學藥": {
        "en": "API / Generic", "category": "生技 / 醫療", "color": "#16a34a",
        "desc": "旭富、神隆、晟德等原料藥（API）與學名藥廠。GLP-1 熱潮 + 專利到期商機驅動。",
        "cagr": "10%", "market_size": "40B USD",
        "indicators": [{"label":"台廠","value":"旭富 / 神隆"},{"label":"產品","value":"API / 學名藥"},{"label":"出口","value":"歐美 + 日本"},{"label":"毛利","value":"30-50%"}],
    },
    "電子零組件/一般": {
        "en": "General Electronics", "category": "連接器 / 被動", "color": "#64748b",
        "desc": "電子零組件次族，含 PCB、連接器、散熱、電池週邊等綜合電子元件廠。為中小型電子供應鏈的集合。",
        "cagr": "8%", "market_size": "—",
        "indicators": [{"label":"範圍","value":"中小電子 OEM"},{"label":"應用","value":"消費 / 工業"},{"label":"毛利","value":"10-20%"},{"label":"景氣","value":"隨終端"}],
    },
    "光學精密元件": {
        "en": "Optical Precision", "category": "面板 / 光電", "color": "#7c3aed",
        "desc": "佳能、亞光、揚明光、玉晶光等光學鏡片、鏡頭、投影、精密光學元件廠。AR/VR、AI 眼鏡興起。",
        "cagr": "10%", "market_size": "6B USD",
        "indicators": [{"label":"應用","value":"手機 / AR / 投影"},{"label":"台廠","value":"佳能 / 亞光"},{"label":"毛利","value":"20-35%"},{"label":"趨勢","value":"AI 眼鏡"}],
    },
    "太陽能/光電板": {
        "en": "Solar Panel", "category": "綠能 / 環保", "color": "#16a34a",
        "desc": "茂迪、聯合再生、元晶為太陽能電池模組廠。台灣屋頂型太陽能 + 海外模組出口。",
        "cagr": "10%", "market_size": "8B USD",
        "indicators": [{"label":"台廠","value":"茂迪 / 聯合再生"},{"label":"應用","value":"屋頂 / 地面"},{"label":"政策","value":"淨零 2050"},{"label":"成本","value":"每年降"}],
    },
    "風電/離岸風電": {
        "en": "Wind Power", "category": "綠能 / 環保", "color": "#0d9488",
        "desc": "世紀風電、世紀鋼為離岸風電水下基礎代表。上緯、天力離岸切入風機零件，政策推動 3.5 GW/年。",
        "cagr": "30%", "market_size": "20B USD",
        "indicators": [{"label":"裝置","value":"3.5 GW/年"},{"label":"台廠","value":"世紀風電 / 上緯"},{"label":"政策","value":"區塊開發 3.0"},{"label":"週期","value":"10 年景氣"}],
    },
    "電動車供應鏈": {
        "en": "EV Supply Chain", "category": "車用 / 機器人", "color": "#84cc16",
        "desc": "Tesla、鴻海 MIH、新勢力 EV 完整供應鏈，含三電系統、車用面板、充電樁、車用半導體。",
        "cagr": "20%", "market_size": "500B USD",
        "indicators": [{"label":"核心","value":"鴻海 MIH / 台達"},{"label":"滲透率","value":"2026E 35%"},{"label":"三電","value":"電機 / 電池 / 電控"},{"label":"台廠卡位","value":"全面"}],
    },
    "晶片封測": {
        "en": "IC Packaging & Test", "category": "封裝 / 測試", "color": "#ea580c",
        "desc": "台灣封測全球市佔 > 50%。日月光、力成、京元電、南茂為四大龍頭。先進封裝 CoWoS 拉動需求。",
        "cagr": "25%", "market_size": "80B USD",
        "indicators": [{"label":"龍頭","value":"日月光 / 力成"},{"label":"全球市佔","value":"50%+"},{"label":"先進封裝","value":"CoWoS"},{"label":"景氣","value":"上升期"}],
    },
    "半導體類比IC": {
        "en": "Analog IC", "category": "AI / 半導體", "color": "#5b8def",
        "desc": "電源管理、感測、訊號鏈類比 IC。茂達、致新、類比科、大中等本土類比 IC 廠。",
        "cagr": "15%", "market_size": "30B USD",
        "indicators": [{"label":"台廠","value":"茂達 / 致新"},{"label":"產品","value":"PMIC / 驅動"},{"label":"毛利","value":"40-50%"},{"label":"AI 受益","value":"高"}],
    },
    "智慧醫療/AI醫學": {
        "en": "AI Medical", "category": "生技 / 醫療", "color": "#0891b2",
        "desc": "AI 影像診斷、基因分析、遠距醫療。宏碁智醫、雲象科技、長佳智能切入臨床 AI 應用。",
        "cagr": "25%", "market_size": "20B USD",
        "indicators": [{"label":"技術","value":"AI 影像 / NLP"},{"label":"台廠","value":"宏碁智醫 / 雲象"},{"label":"認證","value":"FDA / TFDA"},{"label":"階段","value":"商業化初期"}],
    },
    "基因/生技檢測": {
        "en": "Genetics & Diagnostics", "category": "生技 / 醫療", "color": "#14b8a6",
        "desc": "NGS 次世代定序、液態切片、遺傳病檢測。訊聯、基米、慧智生技切入個人化醫療。",
        "cagr": "20%", "market_size": "25B USD",
        "indicators": [{"label":"技術","value":"NGS / 液態切片"},{"label":"台廠","value":"訊聯 / 慧智"},{"label":"應用","value":"癌症 / 遺傳"},{"label":"毛利","value":"50-70%"}],
    },
    "老年長照/銀髮醫療": {
        "en": "Elderly Care", "category": "生技 / 醫療", "color": "#6d28d9",
        "desc": "高齡化社會帶動長照、居家護理、藥局通路需求。大樹、杏一藥局，鳳凰、佑全醫療連鎖。",
        "cagr": "12%", "market_size": "—",
        "indicators": [{"label":"驅動","value":"超高齡社會"},{"label":"龍頭","value":"大樹 / 杏一"},{"label":"政策","value":"長照 3.0"},{"label":"毛利","value":"20-30%"}],
    },
    "美容保健/個人護理": {
        "en": "Beauty & Care", "category": "生技 / 醫療", "color": "#db2777",
        "desc": "麗豐、佐登、達爾膚等美容、面膜、護膚品牌。高毛利、可重複消費、中國市場是關鍵。",
        "cagr": "10%", "market_size": "—",
        "indicators": [{"label":"台廠","value":"麗豐 / 佐登"},{"label":"毛利","value":"50-70%"},{"label":"市場","value":"兩岸 + 東南亞"},{"label":"趨勢","value":"精準護膚"}],
    },
    "新藥研發": {
        "en": "Drug Development", "category": "生技 / 醫療", "color": "#be123c",
        "desc": "新藥研發廠，含臨床各階段。合一（抗體藥）、藥華藥（血癌新藥）、保瑞（收購擴張）為指標。",
        "cagr": "18%", "market_size": "—",
        "indicators": [{"label":"指標","value":"合一 / 藥華藥"},{"label":"授權金","value":"2026 多標的"},{"label":"里程碑","value":"FDA 審批"},{"label":"波動","value":"高"}],
    },
    "動物保健/寵物醫療": {
        "en": "Animal Health", "category": "傳產利基", "color": "#f472b6",
        "desc": "寵物疫苗、動物藥品、寵物食品。少子高齡化驅動，大江生醫、萬達寵物為代表。",
        "cagr": "12%", "market_size": "—",
        "indicators": [{"label":"驅動","value":"少子高齡化"},{"label":"台廠","value":"大江 / 萬達寵物"},{"label":"毛利","value":"30-40%"},{"label":"趨勢","value":"毛孩經濟"}],
    },
    "半導體/晶片代工次族": {
        "en": "Semi Subsector", "category": "AI / 半導體", "color": "#8b5cf6",
        "desc": "中小型半導體設計、製造、封測廠，涵蓋 IC 設計、代工、封測的中段供應鏈。",
        "cagr": "10%", "market_size": "—",
        "indicators": [{"label":"範圍","value":"中小半導體"},{"label":"毛利","value":"20-40%"},{"label":"景氣","value":"隨景氣"},{"label":"技術","value":"成熟製程"}],
    },
    "其他電子/工控": {
        "en": "Other Electronics", "category": "連接器 / 被動", "color": "#475569",
        "desc": "其他電子、工業控制、感測器、安全設備等綜合電子族群。補足主流題材外的中小電子廠。",
        "cagr": "6%", "market_size": "—",
        "indicators": [{"label":"範圍","value":"工控 / 感測"},{"label":"應用","value":"工業 / 監控"},{"label":"毛利","value":"15-25%"},{"label":"景氣","value":"穩定"}],
    },
    "居家修繕/家居用品": {
        "en": "Home Improvement", "category": "建材 / 居家", "color": "#a16207",
        "desc": "櫻花、福興、成霖、詩肯等居家修繕、家居用品族群。受建案交屋、翻修需求影響。",
        "cagr": "5%", "market_size": "—",
        "indicators": [{"label":"龍頭","value":"櫻花 / 成霖"},{"label":"通路","value":"賣場 / 直營"},{"label":"毛利","value":"20-30%"},{"label":"驅動","value":"建案 + 翻修"}],
    },
    "模具/金屬加工": {
        "en": "Metal Processing", "category": "傳產利基", "color": "#64748b",
        "desc": "精密模具、金屬沖壓、螺絲扣件等金屬加工族群。下游含汽車、工業、機械。",
        "cagr": "5%", "market_size": "—",
        "indicators": [{"label":"下游","value":"汽車 / 工業"},{"label":"台廠","value":"永冠 / 亞德客"},{"label":"毛利","value":"15-25%"},{"label":"景氣","value":"隨機械"}],
    },
    "投資控股/租賃": {
        "en": "Holdings & Leasing", "category": "金融", "color": "#0369a1",
        "desc": "中租、和潤、裕融為汽車融資租賃三雄。潤泰、中保科等投控為多元持股。",
        "cagr": "10%", "market_size": "—",
        "indicators": [{"label":"龍頭","value":"中租 / 和潤"},{"label":"業務","value":"汽車融資"},{"label":"殖利率","value":"3-5%"},{"label":"風險","value":"利率敏感"}],
    },
    "寵物/生活周邊": {
        "en": "Pet & Lifestyle", "category": "傳產利基", "color": "#ec4899",
        "desc": "寵物食品、寵物用品、生活周邊用品。毛小孩商機結構性成長。",
        "cagr": "12%", "market_size": "—",
        "indicators": [{"label":"台廠","value":"萬達寵物 / 福懋"},{"label":"ARPU","value":"年增 8-10%"},{"label":"通路","value":"連鎖 + 電商"},{"label":"趨勢","value":"鮮食 + 保健"}],
    },
    "OLED/Micro LED": {
        "en": "OLED / Micro LED", "category": "面板 / 光電", "color": "#9333ea",
        "desc": "OLED 進入中小尺寸主流，Micro LED 為次世代顯示技術。錼創為 Micro LED 核心，友達、群創切入 OLED。",
        "cagr": "25%", "market_size": "30B USD",
        "indicators": [{"label":"技術","value":"OLED / Micro LED"},{"label":"應用","value":"手機 / 穿戴 / 車用"},{"label":"台廠","value":"錼創 / 友達"},{"label":"時程","value":"2026-2028 量產"}],
    },
    "造紙/紙業": {
        "en": "Paper Industry", "category": "傳產利基", "color": "#78350f",
        "desc": "工業用紙、家用紙、包材紙業。永豐餘、華紙、正隆為三雄，ESG 再生紙結構性需求。",
        "cagr": "3%", "market_size": "—",
        "indicators": [{"label":"龍頭","value":"永豐餘 / 華紙"},{"label":"下游","value":"電商包材"},{"label":"殖利率","value":"4-6%"},{"label":"景氣","value":"木漿敏感"}],
    },
    "CDMO/生技製造服務": {
        "en": "CDMO", "category": "生技 / 醫療", "color": "#059669",
        "desc": "合約開發製造 CDMO，承接全球藥廠委外生產訂單。保瑞積極併購擴張，台康生技切入抗體藥 CDMO。",
        "cagr": "22%", "market_size": "60B USD",
        "indicators": [{"label":"龍頭","value":"保瑞 / 台康"},{"label":"駐型","value":"小分子 / 大分子"},{"label":"訂單","value":"GLP-1 熱潮"},{"label":"毛利","value":"30-40%"}],
    },
    "PCB設備/耗材": {
        "en": "PCB Equipment", "category": "封裝 / 測試", "color": "#db2777",
        "desc": "PCB 製造設備、耗材、檢測設備。迅得、群翊、達航為主要 PCB 設備廠。",
        "cagr": "12%", "market_size": "3B USD",
        "indicators": [{"label":"台廠","value":"迅得 / 群翊"},{"label":"下游","value":"PCB 廠"},{"label":"毛利","value":"20-30%"},{"label":"景氣","value":"隨 PCB"}],
    },
    "台積電供應鏈": {
        "en": "TSMC Supply Chain", "category": "AI / 半導體", "color": "#ff7847",
        "desc": "台積電上下游供應鏈，含矽晶圓、廠務工程、特殊氣體、設備與封測。最純粹的台積電擴廠受益族群。",
        "cagr": "20%", "market_size": "—",
        "indicators": [{"label":"核心","value":"TSMC"},{"label":"廠務","value":"漢唐 / 聖暉"},{"label":"擴廠週期","value":"2025-2030"},{"label":"受惠","value":"全面"}],
    },
    "AI基礎設施/資料中心": {
        "en": "AI Infrastructure", "category": "AI / 半導體", "color": "#ea580c",
        "desc": "AI 資料中心硬體整體解決方案，涵蓋伺服器、散熱、網通、電源、機殼全鏈。北美 CSP 資本支出直接受益。",
        "cagr": "40%", "market_size": "250B USD",
        "indicators": [{"label":"驅動","value":"CSP 資本支出"},{"label":"核心台廠","value":"鴻海 / 廣達"},{"label":"滲透率","value":"GB200 2026"},{"label":"訂單能見度","value":"2-3 年"}],
    },
    "無塵室/廠務工程": {
        "en": "Cleanroom", "category": "封裝 / 測試", "color": "#14b8a6",
        "desc": "半導體廠無塵室、機電工程、空調系統。漢唐、聖暉、亞翔為三大廠務龍頭。TSMC、Intel 擴廠直接受益。",
        "cagr": "18%", "market_size": "8B USD",
        "indicators": [{"label":"龍頭","value":"漢唐 / 聖暉 / 亞翔"},{"label":"客戶","value":"TSMC / Intel"},{"label":"毛利","value":"10-15%"},{"label":"訂單","value":"3-5 年能見度"}],
    },
    "環境設備/空汙": {
        "en": "Environmental Equipment", "category": "綠能 / 環保", "color": "#0d9488",
        "desc": "空氣污染防治、廢水處理、廢棄物設備。日友、可寧衛為龍頭，ESG 法規結構性驅動。",
        "cagr": "12%", "market_size": "5B USD",
        "indicators": [{"label":"龍頭","value":"日友 / 可寧衛"},{"label":"驅動","value":"ESG 法規"},{"label":"毛利","value":"30-40%"},{"label":"市場","value":"B2B"}],
    },
    "交通運輸/物流": {
        "en": "Transportation & Logistics", "category": "航運 / 傳產", "color": "#2563eb",
        "desc": "航空、海運、陸運、物流綜合族群。長榮航、華航、台灣高鐵、宅配通為代表。電商物流快速成長。",
        "cagr": "8%", "market_size": "—",
        "indicators": [{"label":"分支","value":"空運 / 陸運 / 物流"},{"label":"電商物流","value":"快速成長"},{"label":"台廠","value":"長榮航 / 大車隊"},{"label":"景氣","value":"消費敏感"}],
    },
    "能源服務/石油燃料": {
        "en": "Energy & Petroleum", "category": "傳產", "color": "#78350f",
        "desc": "石化煉油、加油站、天然氣服務。台塑化、山隆、台汽電為代表。能源轉型期結構性調整。",
        "cagr": "3%", "market_size": "—",
        "indicators": [{"label":"龍頭","value":"台塑化 / 山隆"},{"label":"景氣","value":"油價連動"},{"label":"殖利率","value":"4-6%"},{"label":"趨勢","value":"綠能轉型"}],
    },
    "中小型生技": {
        "en": "Small Biotech", "category": "生技 / 醫療", "color": "#84cc16",
        "desc": "中小型生技醫療族群，涵蓋新藥研發、醫療器材、生技服務等。波動大、題材屬性強。",
        "cagr": "15%", "market_size": "—",
        "indicators": [{"label":"屬性","value":"題材驅動"},{"label":"波動","value":"高"},{"label":"里程碑","value":"臨床進度"},{"label":"風險","value":"本夢比"}],
    },
    "電腦週邊/配件": {
        "en": "PC Peripheral", "category": "消費電子", "color": "#6b7280",
        "desc": "電腦週邊、配件、外接裝置、IPC 小廠。中小型電腦週邊供應鏈集合。",
        "cagr": "5%", "market_size": "—",
        "indicators": [{"label":"範圍","value":"週邊配件"},{"label":"客戶","value":"PC 品牌"},{"label":"毛利","value":"10-20%"},{"label":"景氣","value":"隨 PC"}],
    },
    "利基光電": {
        "en": "Niche Optoelectronics", "category": "面板 / 光電", "color": "#6d28d9",
        "desc": "中小型光電族群，含光儲存、光學元件、LED 背光、觸控等利基光電廠。",
        "cagr": "6%", "market_size": "—",
        "indicators": [{"label":"範圍","value":"光儲存 / 觸控"},{"label":"景氣","value":"隨終端"},{"label":"毛利","value":"10-20%"},{"label":"規模","value":"中小"}],
    },
    "小型通信網路": {
        "en": "Small Telecom", "category": "光通訊 / 網通", "color": "#14b8a6",
        "desc": "中小型通信網路、天線、射頻、網通設備廠。服務利基通訊應用。",
        "cagr": "8%", "market_size": "—",
        "indicators": [{"label":"應用","value":"天線 / 射頻"},{"label":"客戶","value":"網通廠"},{"label":"毛利","value":"15-25%"},{"label":"規模","value":"中小"}],
    },
    "金融證券": {
        "en": "Financial & Securities", "category": "金融", "color": "#0369a1",
        "desc": "非金控金融業，含保險、票券、證券、期貨等獨立金融族群。",
        "cagr": "8%", "market_size": "—",
        "indicators": [{"label":"分支","value":"保險 / 證券 / 期貨"},{"label":"殖利率","value":"4-6%"},{"label":"利率","value":"敏感"},{"label":"台廠","value":"群益證 / 群益期"}],
    },
    "運動休閒": {
        "en": "Sports & Leisure", "category": "運動 / 休閒", "color": "#be185d",
        "desc": "自行車、健身器材、運動用品、休閒鞋。巨大、美利達、喬山為龍頭。",
        "cagr": "7%", "market_size": "—",
        "indicators": [{"label":"龍頭","value":"巨大 / 美利達"},{"label":"市場","value":"歐美 + 中國"},{"label":"毛利","value":"20-30%"},{"label":"趨勢","value":"電助力車"}],
    },
    "食品零售": {
        "en": "Food Retail", "category": "傳產", "color": "#65a30d",
        "desc": "加工食品、醬料、保健食品零售族群。防禦性強、景氣敏感度低。",
        "cagr": "5%", "market_size": "—",
        "indicators": [{"label":"龍頭","value":"德麥 / 黑松"},{"label":"通路","value":"超市 / 電商"},{"label":"毛利","value":"20-30%"},{"label":"防禦性","value":"高"}],
    },
    "其他（多元族群）": {
        "en": "Others / Diversified", "category": "傳產", "color": "#71717a",
        "desc": "多元化控股、冷門投資、其他未歸類族群的集合。屬於未有明確主題的公司。",
        "cagr": "—", "market_size": "—",
        "indicators": [{"label":"範圍","value":"多元"},{"label":"屬性","value":"價值股"},{"label":"殖利率","value":"變動大"},{"label":"分析難度","value":"較高"}],
    },

    # ═══════════════════════════════════════════
    #  新增族群（MyTWC themes 整合 2026-04-24）
    # ═══════════════════════════════════════════
    "5G 通訊": {
        "en": "5G Communications", "category": "光通訊 / 網通", "color": "#0891b2",
        "desc": "5G 基地台、小基站、天線、RF 元件、網通設備全鏈。台廠受惠 Open RAN、企業專網與海外 Tier-1 電信商擴建，"
                "中華電/遠傳/台灣大完成 5G 全島覆蓋，下一波成長在 5G-Advanced 與 6G 預研。",
        "cagr": "12%", "market_size": "80B USD",
        "indicators": [{"label":"台廠龍頭","value":"中華電 / 智邦 / 台揚"},{"label":"技術趨勢","value":"Open RAN / 5G-A"},{"label":"應用","value":"企業專網 / FWA"},{"label":"滲透率","value":"2027E 50%"}],
    },
    "EUV 極紫外光微影": {
        "en": "EUV Lithography", "category": "封裝 / 測試", "color": "#7c3aed",
        "desc": "極紫外光微影為 7nm 以下先進製程關鍵設備，全球獨家由 [[ASML]] 供應。台廠切入 EUV 載台、光罩盒、清洗與周邊耗材，"
                "跟隨台積電 A16/A14 擴產週期放量。",
        "cagr": "20%", "market_size": "40B USD",
        "indicators": [{"label":"獨家設備商","value":"ASML"},{"label":"台廠受惠","value":"家登 / 弘塑"},{"label":"製程節點","value":"3nm / 2nm / A14"},{"label":"訂單週期","value":"2025-2030"}],
    },
    "特斯拉概念股": {
        "en": "Tesla Supply Chain", "category": "車用 / 機器人", "color": "#cc0000",
        "desc": "Tesla 供應鏈是台灣 EV 題材最具體的概念股組合，涵蓋電源、連接器、齒輪傳動、感測器與人形機器人零組件。"
                "台達電為充電樁龍頭；貿聯-KY 為 Model 系列線束獨家；大銀微系統 2024 年切入 Optimus 線性馬達。"
                "Model Y 改款、Optimus 2026 量產、Robotaxi 商業化為三大催化。",
        "cagr": "18%", "market_size": "—",
        "indicators": [{"label":"台廠代表","value":"台達電 / 貿聯-KY / 大銀"},{"label":"催化","value":"Optimus / Robotaxi"},{"label":"客戶","value":"Tesla Model Y/3 / Optimus"},{"label":"風險","value":"Musk 政策 / 銷售波動"}],
    },
    "VCSEL 雷射": {
        "en": "VCSEL Laser", "category": "光通訊 / 網通", "color": "#d946ef",
        "desc": "垂直腔面發射雷射，應用於 3D 感測（Face ID、光學滑鼠）、光通訊（資料中心短距）、車用 LiDAR。"
                "台廠聯亞、穩懋為化合物半導體代工，3D 感測與 CPO 光模組雙引擎拉動。",
        "cagr": "22%", "market_size": "5B USD",
        "indicators": [{"label":"應用","value":"3D 感測 / 資料中心 / LiDAR"},{"label":"台廠","value":"聯亞 / 穩懋"},{"label":"核心客戶","value":"Apple / 光模組廠"},{"label":"趨勢","value":"CPO 整合需求"}],
    },
    "磷化銦/InP": {
        "en": "Indium Phosphide (InP)", "category": "第三代半導體", "color": "#059669",
        "desc": "磷化銦化合物半導體基板，為光通訊、高頻元件與矽光子必備晶圓材料。"
                "CPO、800G/1.6T 光模組量產帶動 InP 需求躍升，下游直接受惠矽光子題材。",
        "cagr": "25%", "market_size": "1.5B USD",
        "indicators": [{"label":"應用","value":"矽光子 / CPO / EML"},{"label":"台廠","value":"聯亞 / IET-KY"},{"label":"驅動","value":"資料中心光互連"},{"label":"競爭","value":"Sumitomo / II-VI"}],
    },
    "資料中心": {
        "en": "Data Center", "category": "AI / 半導體", "color": "#ea580c",
        "desc": "超大規模資料中心供應鏈整體解決方案：從 GPU 伺服器、HBM、液冷、電源、網通交換器到機櫃與機房廠務。"
                "北美 CSP（Meta/Google/AWS/Azure）2025-2027 資本支出年複合 40%+，台廠 ODM 與零組件全面吃貨。",
        "cagr": "35%", "market_size": "300B USD",
        "indicators": [{"label":"CSP 資本支出","value":"2026E +40%"},{"label":"台廠龍頭","value":"鴻海 / 廣達 / 緯創"},{"label":"熱點","value":"液冷 / 800V HVDC / 光互連"},{"label":"訂單能見度","value":"2-3 年"}],
    },
}


# Category 顏色（側邊導覽用）
CATEGORY_COLORS = {
    "AI / 半導體":    "#ff7847",
    "封裝 / 測試":    "#f97316",
    "基板 / PCB":     "#a855f7",
    "散熱 / 電源":    "#0ea5e9",
    "光通訊 / 網通":  "#10b981",
    "連接器 / 被動":  "#6366f1",
    "車用 / 機器人":  "#84cc16",
    "國防 / 資安":    "#dc2626",
    "消費電子":       "#71717a",
    "面板 / 光電":    "#7c3aed",
    "航運 / 傳產":    "#2563eb",
    "金融":           "#0369a1",
    "傳產":           "#525252",
    "生技 / 醫療":    "#16a34a",
    "事件驅動":       "#a3a3a3",
    "第三代半導體":   "#f59e0b",
    "利基零組件":     "#14b8a6",
    "傳產利基":       "#78350f",
    "政策驅動":       "#15803d",
    "電子通路 / 服務": "#4338ca",
    "雲端 / 軟體":    "#7c3aed",
    "運動 / 休閒":    "#be185d",
    "綠能 / 環保":    "#059669",
    "化工 / 特化":    "#9a3412",
    "建材 / 居家":    "#a16207",
    "傳媒 / 文創":    "#a21caf",
}


def get_meta(group_name: str) -> dict:
    """取得題材 meta，沒有則回傳預設值"""
    if group_name in INDUSTRY_META:
        return INDUSTRY_META[group_name]
    return {
        "en": group_name,
        "category": "其他",
        "color": "#64748b",
        "desc": f"「{group_name}」相關概念股，資料彙整中。",
        "cagr": "—",
        "market_size": "—",
        "indicators": [
            {"label": "題材類型", "value": "概念股"},
            {"label": "資料狀態", "value": "彙整中"},
            {"label": "成分股數", "value": ""},
            {"label": "更新頻率", "value": "每日"},
        ],
    }
