"""
台股個股技術亮點與產業排名資料庫
參考：用戶提供 + My-TW-Coverage + 產業研究報告彙整

結構：
  STOCK_HIGHLIGHTS[sym] = {
    "ranking": str,   # 一行產業排名（最顯眼）
    "tech":    str,   # 技術特點 / 護城河描述
    "moat":    str,   # 市場地位補充說明
  }

理念：不求每檔都有，只收「技術/市佔可辨識」的重要個股。
"""

STOCK_HIGHLIGHTS = {
    # ═══════════ 半導體核心 ═══════════
    "2330": {
        "ranking": "先進製程 全球 #1",
        "tech": "3nm 獨家量產、2nm 2026 Q4 上線、CoWoS 產能佔全球 90%+",
        "moat": "北美 CSP / Apple / NVIDIA / AMD 指定代工，技術領先三星兩代",
    },
    "2303": {
        "ranking": "成熟製程 全球 #2",
        "tech": "28nm / 40nm 車用與工控強項、力積電之上",
        "moat": "成熟製程客戶遍佈全球，2026 稼動率回升",
    },
    "6770": {
        "ranking": "DRAM Foundry 台灣 #1",
        "tech": "GaN 代工 2026 擴產 3-4 倍，黃崇仁主導",
        "moat": "台灣唯一 DRAM 代工，車用+工控多元佈局",
    },
    "3711": {
        "ranking": "封測 全球 #1",
        "tech": "CoWoS 外部封測獨家、SoIC 3D 封裝領先",
        "moat": "TSMC 最大 OSAT 夥伴，AI 伺服器核心",
    },
    "2449": {
        "ranking": "IC 測試 全球 #5",
        "tech": "NVIDIA GPU 測試獨家",
        "moat": "AI 晶片測試流程受限，京元獨門技術",
    },
    # ═══════════ ASIC / IP ═══════════
    "3661": {
        "ranking": "ASIC 設計服務 台灣 #1",
        "tech": "AWS Trainium、Meta MTIA、Google TPU 設計合作",
        "moat": "TSMC 旗下子公司，CSP 去輝達化首選",
    },
    "3443": {
        "ranking": "ASIC 設計服務 台灣 #2",
        "tech": "AWS、Microsoft、Tesla Dojo 設計服務",
        "moat": "TSMC VCA 聯盟成員，2nm 設計能力",
    },
    "2454": {
        "ranking": "IC 設計 全球 #4 / 台灣 #1",
        "tech": "Dimensity 9400 旗艦 SoC、5G 數據晶片全球 #1",
        "moat": "手機 SoC 市佔 38%，切入 AI 伺服器 ASIC",
    },
    "2379": {
        "ranking": "網通 IC 全球 #1",
        "tech": "乙太網、WiFi 7、PCIe Switch 全系列",
        "moat": "AI DC 高速傳輸 IC 獨家優勢",
    },
    "5274": {
        "ranking": "BMC 伺服器管理晶片 全球 #1",
        "tech": "獨家 BMC/ServerOn Chip 市占 70%+",
        "moat": "伺服器管理晶片進入門檻極高",
    },
    "3529": {
        "ranking": "非揮發性 IP（eFlash）全球 #1",
        "tech": "嵌入式記憶體 IP 業界標準",
        "moat": "台積電成熟製程必用，授權收入穩定",
    },
    "4966": {
        "ranking": "Display Port / USB IC 全球 #1",
        "tech": "DP / eDP Timing Controller 主流供應",
        "moat": "蘋果 MacBook 獨家 eDP IC",
    },
    "5269": {
        "ranking": "USB Host IC 全球 #1",
        "tech": "AMD 主機板 USB 獨家、PCIe Switch 卡位",
        "moat": "USB 4 / Thunderbolt 規格主導",
    },

    # ═══════════ AI 伺服器 / PCB / 載板 ═══════════
    "2368": {
        "ranking": "高階伺服器 PCB 台股 #1",
        "tech": "載板技術排名：金像電 > 健鼎 > 博智 > 華通",
        "moat": "AI 伺服器核心 PCB 獨家規格，GB200/GB300 核心供應商",
    },
    "3044": {
        "ranking": "HDI / PCB 台灣 #2",
        "tech": "蘋果 iPhone 主板、AI 伺服器 HDI 雙切入",
        "moat": "製程良率業界領先、客戶分散",
    },
    "2313": {
        "ranking": "低軌衛星 PCB 獨門供應",
        "tech": "SpaceX 衛星本體板 + 地面基站板同時吃",
        "moat": "衛星板技術規格與伺服器板完全不同、幾乎無競爭對手",
    },
    "3037": {
        "ranking": "ABF 載板 全球 #1",
        "tech": "AI GPU / CPU 載板主力供應，CoWoS-L 互連",
        "moat": "ABF 全球三雄之首，2026 擴產",
    },
    "8046": {
        "ranking": "ABF 載板 全球 #3",
        "tech": "NVIDIA GPU 載板供應",
        "moat": "產能吃緊，2026 新廠量產",
    },
    "3189": {
        "ranking": "ABF 載板 全球 #4",
        "tech": "AMD / Intel 客戶為主",
        "moat": "ABF 載板寡占市場",
    },
    "2383": {
        "ranking": "CCL 銅箔基板 台灣 #1",
        "tech": "HVLP4 高速低損 CCL，AI 伺服器必用",
        "moat": "2026 Q1 價格季增 10-40%",
    },
    "6274": {
        "ranking": "CCL 銅箔基板 台灣 #2",
        "tech": "AI 伺服器用超低損 CCL",
        "moat": "供需吃緊，漲價能見度高",
    },

    # ═══════════ AI 伺服器代工 / 散熱 / 機殼 ═══════════
    "2382": {
        "ranking": "AI 伺服器 ODM 全球 #1",
        "tech": "NVIDIA DGX/HGX 獨家組裝、GB200 最大贏家",
        "moat": "NVIDIA 首選夥伴，毛利較 Dell/HPE 高",
    },
    "3231": {
        "ranking": "AI 伺服器 ODM 全球 #2",
        "tech": "GB200 / GB300 液冷伺服器組裝",
        "moat": "與 NVIDIA 合作 20+ 年",
    },
    "2317": {
        "ranking": "全球最大 EMS（電子代工）",
        "tech": "蘋果 iPhone 組裝 70%+、AI 伺服器新 B200 GB200",
        "moat": "全球產能規模最大、印度 + 墨西哥 + 越南分散",
    },
    "6669": {
        "ranking": "CSP 直營 AI 伺服器 #1",
        "tech": "Meta / Microsoft / AWS 雲端 AI 機櫃獨家",
        "moat": "Open Compute Project 主導成員",
    },
    "2356": {
        "ranking": "AI 伺服器 ODM 前五",
        "tech": "NVIDIA AI Server、HPE 代工",
        "moat": "打入 NVIDIA GB200 供應鏈",
    },
    "3017": {
        "ranking": "散熱模組 全球 #1",
        "tech": "3DVC、液冷冷板、均熱板技術領先",
        "moat": "NVIDIA 獨家液冷模組，AI 伺服器 BOM 大增",
    },
    "3324": {
        "ranking": "散熱模組 全球 #2",
        "tech": "液冷 CDU + 冷板",
        "moat": "AMD / NVIDIA 雙客戶",
    },
    "3653": {
        "ranking": "冷板散熱 全球 #3",
        "tech": "CDU 冷板液冷、手機均熱板",
        "moat": "蘋果 MacBook + AI 伺服器雙引擎",
    },
    "8996": {
        "ranking": "熱交換器 / 氫能 獨家",
        "tech": "AI DC 液冷熱交換器、氫能燃料電池",
        "moat": "CDU 熱交換器關鍵供應商",
    },
    "8210": {
        "ranking": "伺服器機殼 台灣 #1",
        "tech": "GB200 NVL72 機櫃、鑽石塗層強度業界領先",
        "moat": "毛利高、客戶集中在 NVIDIA + CSP",
    },
    "3515": {
        "ranking": "AI 主機板 全球前三",
        "tech": "NVIDIA B100/B200 主機板設計",
        "moat": "華擎品牌 + AI 伺服器主板雙引擎",
    },
    "3693": {
        "ranking": "伺服器機殼 前五",
        "tech": "Rackmount 機殼代工",
        "moat": "台系二線機殼廠",
    },

    # ═══════════ 電源 / 重電 / 連接器 ═══════════
    "2308": {
        "ranking": "電源供應器 全球 #1",
        "tech": "12kW / 33kW 伺服器電源、800V HVDC、液冷 CDU",
        "moat": "NVIDIA 指定電源供應、全球工業自動化龍頭",
    },
    "1519": {
        "ranking": "重電三雄之一",
        "tech": "GIS 氣體絕緣開關設備、海底電纜",
        "moat": "台電 5,645 億強韌電網受惠",
    },
    "1513": {
        "ranking": "重電三雄之一",
        "tech": "智慧電錶、儲能 PCS",
        "moat": "台電 300 萬戶 AMI 標案得主",
    },
    "1503": {
        "ranking": "重電三雄之一",
        "tech": "變壓器 + 配電設備",
        "moat": "AI DC 電力升級直接受惠",
    },
    "1605": {
        "ranking": "電線電纜 台灣 #1、海底電纜 獨家",
        "tech": "與丹麥 NKT 合資高雄海纜廠 180 億投資",
        "moat": "台灣唯一離岸風電海纜製造商，AI DC 海底互連受惠",
    },
    "3533": {
        "ranking": "高速連接器 台灣 #1",
        "tech": "224G SerDes、CPU / GPU Socket、AI 伺服器內部互連",
        "moat": "NVIDIA 獨家、毛利高",
    },
    "3665": {
        "ranking": "高速線纜 全球 #1",
        "tech": "AI 伺服器高速 Cable、汽車線束",
        "moat": "NVIDIA GB200 獨家互連線、TSMC 廠務配線",
    },
    "2327": {
        "ranking": "MLCC / 晶片電阻 全球 #3",
        "tech": "車用、AI 伺服器高階被動元件",
        "moat": "併購 Murata 汽車事業，毛利升級",
    },
    "2492": {
        "ranking": "MLCC 全球 #5",
        "tech": "AI 伺服器高頻高壓電容",
        "moat": "產能擴張中",
    },

    # ═══════════ 光通訊 / CPO ═══════════
    "3081": {
        "ranking": "矽光子 InP 雷射 獨家",
        "tech": "1.6T 光收發模組 InP 雷射晶片自製",
        "moat": "毛利 50%+，Google / AWS 光引擎合作",
    },
    "2455": {
        "ranking": "GaAs 代工 全球 #2",
        "tech": "砷化鎵磊晶、WiFi PA、CPO 光引擎",
        "moat": "CPO 矽光子七劍客之一",
    },
    "3105": {
        "ranking": "GaAs 代工 全球 #1",
        "tech": "砷化鎵 RF 代工、GaN 擴產、CPO 封裝",
        "moat": "全球 60% GaAs 代工市占",
    },
    "3363": {
        "ranking": "光纖被動元件 全球前三",
        "tech": "AWG、WDM 器件、光連接器",
        "moat": "矽光子模組組裝切入",
    },

    # ═══════════ 生技 / 航運 / 傳產 ═══════════
    "6446": {
        "ranking": "新藥授權收入 台灣 #1",
        "tech": "骨髓增殖性腫瘤 P3、ET 適應症通過 FDA",
        "moat": "台灣少數有全球商品化新藥",
    },
    "6472": {
        "ranking": "CDMO 台灣 #1",
        "tech": "併購策略：Impax、Upsher-Smith、Promesa",
        "moat": "GLP-1 委外製造受惠",
    },
    "2603": {
        "ranking": "貨櫃航運 台灣 #1 / 全球前五",
        "tech": "新船投入多、綠色燃料領先",
        "moat": "紅海危機 + 巴拿馬運河限制推升運價",
    },
    "2609": {
        "ranking": "貨櫃航運 台灣 #2",
        "tech": "遠東 - 北美主力航線",
        "moat": "現金殖利率高",
    },
    "2615": {
        "ranking": "近洋航運 台灣 #1",
        "tech": "亞洲區間航線龍頭",
        "moat": "東南亞貿易回暖受惠",
    },
    "2002": {
        "ranking": "鋼鐵 台灣 #1",
        "tech": "冷軋 / 電磁鋼片、碳鋼",
        "moat": "中鋼集團整合、政府大股東",
    },
    "1216": {
        "ranking": "食品 台灣 #1",
        "tech": "7-ELEVEN 通路、飲料 / 速食 / 休閒食品",
        "moat": "通路綜合實力無敵",
    },
    "2049": {
        "ranking": "滾珠螺桿 全球 #2",
        "tech": "工具機精密傳動、人形機器人諧波減速機",
        "moat": "僅次於日本 THK、人形機器人新客戶群",
    },
    "3008": {
        "ranking": "手機鏡頭 全球 #1",
        "tech": "七片鏡頭、玻塑混合鏡頭、AR 鏡頭",
        "moat": "蘋果獨家、毛利 65%+",
    },
    "6488": {
        "ranking": "矽晶圓 全球 #3",
        "tech": "12 吋矽晶圓、SiC 基板、德州新廠",
        "moat": "TSMC 主要晶圓供應商",
    },
    "2881": {
        "ranking": "金控 台灣獲利 #1",
        "tech": "壽險 + 銀行 + 證券完整佈局",
        "moat": "富邦集團綜合效益",
    },
    "2882": {
        "ranking": "金控 壽險 #1",
        "tech": "國壽 + 國泰世華銀行",
        "moat": "壽險資產規模最大",
    },
    "8299": {
        "ranking": "NAND 控制晶片 全球 #1",
        "tech": "aiDAPTIV+ 將 SSD 模擬為 DRAM、AI 伺服器獨家",
        "moat": "NAND 主控 IP 自研、潘健成領軍",
    },
    "2408": {
        "ranking": "DRAM 台灣 #1",
        "tech": "10nm DDR4 / DDR5 量產",
        "moat": "南亞科集團、2026 DRAM 漲價受惠",
    },
    "2344": {
        "ranking": "Niche DRAM 全球 #1",
        "tech": "Niche DRAM、NOR Flash 利基型記憶體",
        "moat": "車用 / 工控利基市場地位穩固",
    },
    "2345": {
        "ranking": "企業網通交換器 全球 #1",
        "tech": "800G / 1.6T Switch、白牌交換器獨家",
        "moat": "Meta / Microsoft 雲端交換器指定",
    },
    "6285": {
        "ranking": "網通 ODM 全球 #2",
        "tech": "WiFi 7 路由器、衛星 Gateway",
        "moat": "SpaceX 地面終端供應商",
    },

    # ═══════════ Round 2：第三代半導體 / 設備 / 工具機 ═══════════
    "3105b": {},  # placeholder to keep dict valid if duplicated
    "3707": {
        "ranking": "SiC 代工 台灣 #1",
        "tech": "碳化矽 6 吋 → 8 吋磊晶代工",
        "moat": "Wolfspeed 重整後台廠轉單首選",
    },
    "3016": {
        "ranking": "SiC / GaN 磊晶 台灣 #1",
        "tech": "砷化鎵磊晶 + 碳化矽 6 吋",
        "moat": "化合物半導體磊晶技術領先",
    },
    "8086": {
        "ranking": "砷化鎵代工 全球 #3",
        "tech": "WiFi PA 晶圓代工",
        "moat": "穩懋之外台灣第二選",
    },
    "6488b": {},  # 環球晶 already defined? check
    "5483": {
        "ranking": "太陽能矽晶圓 全球前三",
        "tech": "單晶 / 多晶矽晶圓、半導體晶圓再生",
        "moat": "環球晶母公司",
    },
    "6182": {
        "ranking": "矽晶圓 台灣 #3 / GaN 基板卡位",
        "tech": "8 吋 / 12 吋矽晶圓、GaN-on-Si",
        "moat": "GaN 切入 EV 快充市場",
    },
    "3042": {
        "ranking": "石英元件 全球 TCXO #1",
        "tech": "高頻低相噪 TCXO / OCXO",
        "moat": "5G / 衛星 / AI 伺服器時脈元件獨家",
    },
    "3563": {
        "ranking": "PCB AOI 設備 全球 #1",
        "tech": "AOI 檢測、無塵室自動化",
        "moat": "台廠 PCB / 半導體 AOI 標配",
    },
    "6223": {
        "ranking": "探針卡 全球前五",
        "tech": "半導體測試探針",
        "moat": "先進封裝測試升級受惠",
    },
    "6515": {
        "ranking": "半導體測試介面 全球 #1",
        "tech": "高頻測試 socket、HBM 測試",
        "moat": "AI GPU 測試吃重",
    },
    "6510": {
        "ranking": "測試探針卡 台灣 #1",
        "tech": "MEMS 探針卡、高階 IC 測試",
        "moat": "TSMC 指定測試供應",
    },
    "2360": {
        "ranking": "ATE 測試設備 全球前五",
        "tech": "電源、訊號測試平台",
        "moat": "車用 / AI 測試升級",
    },
    "6138": {
        "ranking": "功率 IC 台灣 #1",
        "tech": "MOSFET、電源管理 IC",
        "moat": "EV / 快充 / AI DC 電源 IC 核心",
    },
    "6435": {
        "ranking": "功率元件 台灣 #2",
        "tech": "MOSFET 分離元件",
        "moat": "車用 + 消費電子雙引擎",
    },
    "6415": {
        "ranking": "電源管理 IC 全球前十",
        "tech": "DC-DC 轉換、AI 伺服器 PMIC",
        "moat": "千金股 + 高毛利",
    },
    "3034": {
        "ranking": "顯示 IC 全球 #3",
        "tech": "Driver IC、Tcon、車用顯示",
        "moat": "蘋果 MacBook eDP IC 獨家",
    },
    "5274": {
        "ranking": "BMC 伺服器管理晶片 全球 #1",
        "tech": "ServerOn Chip、AI 伺服器管理 IC",
        "moat": "市占 70%+，進入門檻極高",
    },
    "3017": {  # 奇鋐 (override)
        "ranking": "散熱模組 全球 #1",
        "tech": "3DVC、液冷冷板、均熱板",
        "moat": "NVIDIA 獨家液冷模組供應商",
    },

    # ═══════════ 工具機 / 機器人 / 精密機構 ═══════════
    "1597": {
        "ranking": "線性滑軌 全球 #3",
        "tech": "精密直線傳動",
        "moat": "上銀主要競爭對手、機器人卡位",
    },
    "4576": {
        "ranking": "線性馬達 台灣 #1",
        "tech": "PMSM 線性馬達、機器人關節",
        "moat": "人形機器人供應鏈",
    },
    "1590": {
        "ranking": "氣動元件 全球 #3",
        "tech": "氣壓缸、電磁閥",
        "moat": "自動化基礎元件、毛利高",
    },
    "9921": {
        "ranking": "自行車 全球 #1",
        "tech": "Giant / Liv 品牌、碳纖維車架",
        "moat": "台灣自行車產業聚落核心",
    },
    "9914": {
        "ranking": "自行車 全球 #3",
        "tech": "Merida 品牌、電動自行車",
        "moat": "歐洲 + 日本市場強",
    },

    # ═══════════ 車用電子 / EV ═══════════
    "1319": {
        "ranking": "車燈 AM 全球 #1",
        "tech": "保險桿、水箱罩、車燈模組",
        "moat": "美國 AM 保修件市占第一",
    },
    "1536": {
        "ranking": "EV 減速器齒輪 全球領先",
        "tech": "Tesla Model 3/Y 齒輪獨家",
        "moat": "Tesla 減速機殼獨家供應",
    },
    "2231": {
        "ranking": "胎壓偵測 TPMS 全球 #1",
        "tech": "TPMS 系統、車用感測",
        "moat": "北美 AM 市占 60%+",
    },

    # ═══════════ 生技醫療 / CDMO ═══════════
    "4743": {
        "ranking": "過敏異位性皮膚炎新藥 台灣領先",
        "tech": "FB825 單株抗體 P3 進行中",
        "moat": "全球前三大適應症新藥",
    },
    "4147": {
        "ranking": "愛滋新藥 全球上市",
        "tech": "TMB-355 單株抗體",
        "moat": "全球少數商品化台灣新藥",
    },
    "6589": {
        "ranking": "疫苗 CDMO 台灣 #1",
        "tech": "mRNA + 蛋白疫苗 CDMO",
        "moat": "2026 桃園新廠量產",
    },
    "4746": {
        "ranking": "活性藥物原料 全球前十",
        "tech": "API 原料藥代工",
        "moat": "高階 API 委外受惠",
    },

    # ═══════════ 航運 / 傳產 / 食品 ═══════════
    "2606": {
        "ranking": "散裝航運 台灣 #1",
        "tech": "海岬型 / 巴拿馬型船隊",
        "moat": "BDI 強勢受惠",
    },
    "2637": {
        "ranking": "散裝航運 台灣 #2",
        "tech": "海岬型 / 超極限型",
        "moat": "新船投入產能擴張",
    },
    "2618": {
        "ranking": "國際航空 台灣 #1",
        "tech": "長榮航 767 / 787 機隊",
        "moat": "北美航線獨家、後疫情復甦強",
    },
    "2610": {
        "ranking": "國際航空 台灣 #2",
        "tech": "華航 A350 長程機隊",
        "moat": "兩岸航線復航受惠",
    },
    "1215": {
        "ranking": "畜禽飼料 台灣 #1",
        "tech": "卜蜂集團、垂直整合養殖",
        "moat": "東南亞市場強",
    },
    "1210": {
        "ranking": "食品 + 飼料 台灣 #2",
        "tech": "大成集團、雞肉加工",
        "moat": "餐飲通路 B2B 強",
    },

    # ═══════════ 金融 / 地產 ═══════════
    "2884": {
        "ranking": "數位金融 台灣 #1",
        "tech": "玉山金控、數位銀行領先",
        "moat": "數位用戶體驗口碑佳",
    },
    "2891": {
        "ranking": "金控 台灣前三",
        "tech": "中信金控、海外佈局廣",
        "moat": "併購日本、泰國銀行",
    },
    "5880": {
        "ranking": "公股金控 台灣前五",
        "tech": "合庫金、中小企業放款",
        "moat": "公股穩定配息",
    },
    "2542": {
        "ranking": "營建股 台灣 #1",
        "tech": "興富發建設、都更題材",
        "moat": "推案量大、品牌知名",
    },
    "5522": {
        "ranking": "營建資產 台灣前五",
        "tech": "遠雄建設、企業總部開發",
        "moat": "土地資產豐厚",
    },

    # ═══════════ 紡織 / 生活消費 ═══════════
    "1476": {
        "ranking": "機能布 全球 #1",
        "tech": "Nike / Lululemon 機能布獨家",
        "moat": "越南產能完整、毛利 25%+",
    },
    "1477": {
        "ranking": "成衣代工 全球前五",
        "tech": "Uniqlo / Gap 代工",
        "moat": "東南亞供應鏈分散",
    },
    "1736": {
        "ranking": "健身器材 全球 #3",
        "tech": "跑步機 / 重訓器材",
        "moat": "Matrix / Johnson 品牌",
    },
    "1707": {
        "ranking": "靈芝保健 台灣 #1",
        "tech": "葡萄王靈芝、紅麴發酵",
        "moat": "通路 + 品牌雙強",
    },

    # ═══════════ LED / 光電 / 面板 ═══════════
    "3714": {
        "ranking": "LED + 矽光子 整合",
        "tech": "Mini LED / Micro LED 磊晶",
        "moat": "蘋果 Vision Pro Micro LED 供應",
    },
    "3481": {
        "ranking": "面板 台灣 #2 / OLED 卡位",
        "tech": "鴻海系面板 + OLED 切入",
        "moat": "夏普 + 群創整合效益",
    },
    "2409": {
        "ranking": "面板 台灣 #1 / Micro LED",
        "tech": "LCD + OLED + Micro LED",
        "moat": "Apple Vision Pro 次代 Micro LED 供應",
    },

    # ═══════════ Round 3：更多利基與熱門個股 ═══════════
    "3532": {"ranking": "玻璃基板 GCS 先行者", "tech": "半導體玻璃基板、手機面板玻璃", "moat": "台勝科受惠先進封裝玻璃化"},
    "6532": {"ranking": "網通 IC 前五", "tech": "WiFi 7 / 藍牙 IC", "moat": "瑞昱之外台廠選擇"},
    "4771": {"ranking": "觸媒化學 台灣領先", "tech": "石化觸媒、ICT 化學品", "moat": "半導體擴廠受惠"},
    "4773": {"ranking": "紡織機能布 全球客戶", "tech": "高機能運動布", "moat": "Nike / Lululemon 供應鏈"},
    "6180": {"ranking": "線上遊戲 台灣 #1", "tech": "Gash 支付 + 新仙劍奇俠傳", "moat": "遊戲 + 支付雙引擎"},
    "3293": {"ranking": "博奕遊戲 全球 #2", "tech": "Live22 博奕平台、東南亞出海", "moat": "鈊象，毛利 60%+ 現金牛"},
    "5478": {"ranking": "老牌遊戲廠 台灣 #1", "tech": "智冠仙劍 / 金庸 IP", "moat": "老牌 IP 授權收入"},
    "2727": {"ranking": "連鎖餐飲 台灣 #1", "tech": "王品集團、多品牌策略", "moat": "中高端餐飲通路"},
    "2731": {"ranking": "旅遊通路 台灣 #1", "tech": "雄獅旅行社、海外出團", "moat": "疫後復甦最快"},
    "5706": {"ranking": "廉航旅遊 台灣 #1", "tech": "鳳凰旅行社、海外套裝", "moat": "出團量全台前三"},
    "2498": {"ranking": "品牌手機 台灣歷史 #1", "tech": "宏達電 VR Focus 3", "moat": "VR 硬體 + 區塊鏈轉型"},
    "8454": {"ranking": "電商 台灣 #1", "tech": "momo 富邦媒、倉儲物流自建", "moat": "快到貨 6 小時為壁壘"},
    "8044": {"ranking": "電商 台灣 #2", "tech": "PChome 網路家庭", "moat": "B2B 通路 + 支付"},
    "6542": {"ranking": "遊戲代理 台灣前三", "tech": "隆中海外遊戲代理", "moat": "中日韓 IP 代理"},
    "4743": {"ranking": "新藥 台灣領先", "tech": "合一 FB825 全球 P3", "moat": "異位性皮膚炎 + 過敏新藥"},
    "2337": {"ranking": "Niche Flash 全球 #1", "tech": "旺宏 NOR Flash、ROM 車用", "moat": "車用 + 工控 Flash 獨家"},
    "8069": {"ranking": "被動元件 前五", "tech": "元太電子紙", "moat": "Kindle 獨家、電子紙全球 #1"},
    "1802": {"ranking": "家用電器 台灣 #1", "tech": "台玻、玻璃製品", "moat": "建築玻璃市佔高"},
    "2393": {"ranking": "億光電子 LED 前三", "tech": "LED 封裝、Mini LED", "moat": "車用 LED + 感測器"},
    "2404": {"ranking": "潔淨室工程 台灣 #1", "tech": "漢唐半導體廠務工程", "moat": "TSMC 擴廠獨家"},
    "6196": {"ranking": "半導體廠務 前三", "tech": "帆宣工程、晶圓廠設備", "moat": "TSMC 擴廠受惠"},
    "5536": {"ranking": "廠務設計 前五", "tech": "聖暉潔淨室設計", "moat": "東南亞市場擴張"},
    "2059": {"ranking": "滑軌 全球 #3", "tech": "川湖伺服器滑軌", "moat": "伺服器機架必備、NVIDIA 供應"},
    "2421": {"ranking": "風扇 全球 #2", "tech": "建準散熱風扇", "moat": "筆電 / 伺服器風扇獨家"},
    "6230": {"ranking": "散熱風扇 前三", "tech": "尼德科超眾，Nidec 子公司", "moat": "NVIDIA 伺服器風扇"},
    "2474": {"ranking": "金屬機殼 全球 #1", "tech": "可成 iPhone 機殼", "moat": "蘋果機殼主供應"},
    "3711": {"ranking": "封測 全球 #1 / ASE 集團", "tech": "CoWoS 外部封裝獨家、AI 晶片受惠", "moat": "全球最大 OSAT"},
    "2454b": {},  # placeholder
    "3711b": {},  # placeholder
    "6266": {"ranking": "泰詠電子 IC 設計", "tech": "電源管理 + 驅動 IC", "moat": "車用 + 通訊"},
    "3406": {"ranking": "玉晶光 光學鏡頭 #2", "tech": "iPhone 鏡頭次主力", "moat": "大立光備援供應"},
    "4979": {"ranking": "矽光子七劍客", "tech": "華星光光通訊模組", "moat": "AI 光收發模組獨家台廠"},
    "4977": {"ranking": "眾達-KY 光模組", "tech": "高速光收發模組", "moat": "400G / 800G 卡位"},
    "6442": {"ranking": "光聖 光通訊元件", "tech": "光纖跳接 / 模組", "moat": "矽光子七劍客"},
    "3163": {"ranking": "波若威 光通訊", "tech": "WDM 被動元件", "moat": "矽光子七劍客"},
    "4971": {"ranking": "IET-KY 光通訊", "tech": "VCSEL 光引擎", "moat": "矽光子七劍客"},
    "2634": {"ranking": "航太 台灣 #1", "tech": "漢翔軍機維修、F-16V", "moat": "國防自主政策受惠"},
    "2645": {"ranking": "航太維修 台灣 #2", "tech": "長榮航太維修", "moat": "波音 / 空巴維修業務"},
    "2208": {"ranking": "軍艦製造 台灣 #1", "tech": "台船潛艦國造、勤務艦", "moat": "國艦國造獨家"},
    "8033": {"ranking": "無人機 台灣 #1", "tech": "雷虎科技軍用無人機", "moat": "國防無人機國家隊"},
    "5371": {"ranking": "無人機 前三", "tech": "中光電投影 + 無人機", "moat": "國防標案受惠"},
    "6752": {"ranking": "軍用無人機 前三", "tech": "雷虎軍用無人載具", "moat": "國家隊成員"},
    "6462": {"ranking": "指紋辨識 IC 全球 #2", "tech": "神盾指紋 IC、手機 + 車用", "moat": "手機生物辨識主力"},
    "6214": {"ranking": "資訊服務 台灣 #1", "tech": "精誠企業 SI、資安服務", "moat": "政府 + 金融 SI 主力"},
    "3029": {"ranking": "資安代理 台灣 #1", "tech": "零壹資訊安全產品代理", "moat": "Palo Alto / Fortinet 代理"},

    # --- 航運 / 鋼鐵 / 塑化更多 ---
    "1301": {"ranking": "塑化 台灣 #1", "tech": "台塑乙烯、PVC、PP", "moat": "台塑集團母公司"},
    "1326": {"ranking": "塑化 台灣 #2", "tech": "台化芳香烴、PS、PE", "moat": "下游產品線完整"},
    "1303": {"ranking": "塑化 台灣 #3", "tech": "南亞 PVC、銅箔、電子材料", "moat": "電子材料切入半導體"},
    "1101": {"ranking": "水泥 台灣 #1", "tech": "台泥水泥 + 能源轉型", "moat": "儲能 + 電池佈局"},
    "1102": {"ranking": "水泥 台灣 #2", "tech": "亞泥水泥 + 環保材料", "moat": "遠東集團"},
    "2015": {"ranking": "熱軋 + 電弧爐 前三", "tech": "豐興鋼鐵，電弧爐製程", "moat": "ESG 低碳鋼材"},
    "2027": {"ranking": "不鏽鋼 台灣 #1", "tech": "大成鋼不鏽鋼板", "moat": "全球不鏽鋼出口前列"},

    # --- 生技醫療更多 ---
    "6547": {"ranking": "疫苗 台灣 #1", "tech": "高端 mRNA + 蛋白次單位", "moat": "COVID 疫苗商品化"},
    "4142": {"ranking": "疫苗 台灣 #2", "tech": "國光生技流感疫苗", "moat": "在地流感疫苗獨家"},
    "4104": {"ranking": "醫材 台灣 #1", "tech": "佳醫骨材 + 血液透析", "moat": "洗腎市場壟斷"},
    "4175": {"ranking": "藥局連鎖 台灣 #1", "tech": "杏一藥局 500+ 店", "moat": "銀髮經濟 + 連鎖"},
    "6469": {"ranking": "藥局連鎖 台灣 #2", "tech": "大樹藥局、連鎖擴張", "moat": "北部主力市場"},

    # --- 食品 / 飲料 / 通路 ---
    "1227": {"ranking": "食用油 台灣 #1", "tech": "佳格得意的一天", "moat": "高端食用油品牌"},
    "1231": {"ranking": "休閒食品 台灣 #1", "tech": "聯華可樂果、卡迪那", "moat": "零食通路品牌強"},
    "9921": {"ranking": "自行車 全球 #1", "tech": "Giant / Liv 品牌、碳纖維", "moat": "自行車聚落核心"},
    "2723": {"ranking": "早餐連鎖 台灣 #1", "tech": "美食-KY 85°C", "moat": "兩岸烘焙連鎖"},

    # --- 航運貨櫃三雄 ---
    "2603b": {},  # already defined

    # ═══════════ Round 4（/loop 擴充）：金融 / 通路 / 傳產重點補 ═══════════
    "2912": {"ranking": "超商 台灣 #1", "tech": "7-ELEVEN 6800+ 店、統一集團通路王", "moat": "全台密度最高、OMO 整合"},
    "2207": {"ranking": "汽車經銷 台灣 #1", "tech": "和泰豐田、Lexus 代理", "moat": "市佔 >30%、品牌忠誠度高"},
    "4958": {"ranking": "PCB 全球 #1", "tech": "臻鼎-KY、iPhone SLP 主供應", "moat": "鴻海集團、SLP + AI 伺服器"},
    "5871": {"ranking": "租賃 台灣 #1", "tech": "中租-KY 車輛 + 設備融資", "moat": "中小企業資金核心"},
    "2886": {"ranking": "公股金控 海外第一", "tech": "兆豐金海外分行 30+ 國", "moat": "外匯業務台灣最強"},
    "2885": {"ranking": "證券 台灣 #1", "tech": "元大金、元大證券市佔 15%+", "moat": "國民 ETF 推動者"},
    "2892": {"ranking": "公股金控 穩健配息", "tech": "第一金、海外佈局中", "moat": "公股配息穩定"},
    "2887": {"ranking": "數位金融 前五", "tech": "台新銀行、Richart 數位品牌", "moat": "年輕族群佈局"},
    "2890": {"ranking": "金控 前十", "tech": "永豐金、大數據應用", "moat": "數位轉型積極"},
    "2883": {"ranking": "金控 前十", "tech": "開發金 + 凱基金整合", "moat": "證券 + 人壽雙引擎"},
    "2880": {"ranking": "公股金控 前十", "tech": "華南金、中小企業放款", "moat": "公股穩健經營"},
    "1402": {"ranking": "化纖 全球 #3", "tech": "遠東新聚酯、寶特瓶回收", "moat": "ESG 再生聚酯領先"},
    "2106": {"ranking": "輪胎 台灣 #2", "tech": "建大中國 + 印尼佈局", "moat": "機車胎全球前五"},
    "2105": {"ranking": "輪胎 台灣 #1", "tech": "正新輪胎 MAXXIS 品牌", "moat": "全球前十大輪胎廠"},
    "1904": {"ranking": "工業用紙 台灣 #1", "tech": "正隆紙箱、電商包裝", "moat": "循環回收體系完整"},
    "1905": {"ranking": "文化用紙 台灣 #1", "tech": "華紙白紙板、環保紙", "moat": "永豐餘集團垂直整合"},
    "1907": {"ranking": "紙類綜合 台灣 #1", "tech": "永豐餘、生質材料延伸", "moat": "碳纖維 / 紙基塑料切入"},
    "1717": {"ranking": "特用化學 台灣 #1", "tech": "長興化工、電子化學品", "moat": "半導體化學品國產化"},
    "8046b": {},  # already
    "2201": {"ranking": "國產車 台灣 #1", "tech": "裕隆納智捷、MIH 電動車", "moat": "MIH 電動車平台主導"},
    "3035": {"ranking": "IC 設計服務老牌", "tech": "智原科技、ASIC 設計服務", "moat": "聯電子公司、老牌 ASIC"},
    "4915": {"ranking": "滑鼠鍵盤 全球 #2", "tech": "致伸科技、羅技 / HP 代工", "moat": "遊戲鍵鼠 OEM 主力"},
    "6183": {"ranking": "電子發票 獨家", "tech": "關貿網路、政府電子發票平台", "moat": "法規壟斷性"},
    "3596": {"ranking": "網通代工 前五", "tech": "智易寬頻 + Router 代工", "moat": "鴻海集團、海外成長"},
    "3380": {"ranking": "企業網通 前五", "tech": "明泰 Switch + ONU 代工", "moat": "Cisco / Commscope 代工"},
    "2332": {"ranking": "家用路由器 全球 #3", "tech": "友訊 D-Link 品牌", "moat": "消費網通品牌度高"},
    "5388": {"ranking": "企業網通 台灣 #3", "tech": "中磊 Cisco 代工 + 衛星", "moat": "衛星 Gateway 切入"},
    "1560": {"ranking": "研磨材料 台灣 #1", "tech": "中砂半導體 CMP 耗材", "moat": "TSMC / 英特爾 CMP 材料"},
    "2388": {"ranking": "IC 設計老牌", "tech": "威盛電子、Centaur CPU", "moat": "老牌 IC 設計轉型 AI 車用"},
    "2204": {"ranking": "商用車 台灣 #1", "tech": "中華汽車商用車代工", "moat": "電動商用車切入"},
    "6919": {"ranking": "離岸風電鋼構 台灣 #1", "tech": "世紀鋼離岸風機基樁", "moat": "台灣離岸風電獨家"},
    "8341": {"ranking": "醫療廢棄物 台灣 #1", "tech": "日友焚化處理", "moat": "環保法規准入壟斷"},
    "8473": {"ranking": "再生水 台灣 #1", "tech": "山林水水處理 BOT", "moat": "TSMC 再生水案場"},
    "6189": {"ranking": "豐藝電子 IC 通路", "tech": "消費 IC 通路、顯示驅動 IC", "moat": "韓日系代理"},
    "3036b": {},  # already
    "6605": {"ranking": "帝寶 車燈 #1", "tech": "車燈 AM 零件，北美為主力市場", "moat": "智慧頭燈 LED 模組"},
    "5347": {"ranking": "世界先進 成熟製程", "tech": "8 吋晶圓代工，PMIC / 驅動 IC", "moat": "TSMC 旗下子公司"},
    "3034b": {},  # already
    "2201b": {},  # already
    "6526": {"ranking": "達發科技 IC 設計", "tech": "網通 SoC、連發科子公司", "moat": "Wi-Fi 7 切入"},
    "8083": {"ranking": "瑞穎 滾珠螺桿", "tech": "精密機構、工具機核心零件", "moat": "上銀之外台灣選擇"},
    "4763": {"ranking": "材料-KY 醫材", "tech": "NBR / 乳膠手套", "moat": "全球前五手套廠"},
    "2303b": {},  # already

    # ═══════════ Round 4（loop 第二輪補充）═══════════
    "6290": {"ranking": "連接線模組 前十", "tech": "良維連接線、Type-C 線材", "moat": "筆電 + AI 伺服器線材供應"},
    "2312": {"ranking": "電子代工 前五", "tech": "金寶印表機 + 儲能系統組裝", "moat": "仁寶集團、儲能 BESS 切入"},
    "6139": {"ranking": "無塵室工程 前三", "tech": "亞翔半導體廠務", "moat": "TSMC 海外新廠工程受惠"},
    "6239": {"ranking": "封測 全球 #8", "tech": "力成記憶體封測、車用 IC 封測", "moat": "DRAM / NAND 封測主力"},
    "2402": {"ranking": "FPC 軟板 前五", "tech": "毅嘉車用 FPC、Apple Watch 供應", "moat": "穿戴 + 車用雙引擎"},
    "3026": {"ranking": "被動元件 前十", "tech": "禾伸堂 MLCC、積層電容", "moat": "車用 + 工控利基"},
    "3138": {"ranking": "射頻天線 前三", "tech": "耀登 5G / 衛星 / 測試天線", "moat": "低軌衛星地面站天線獨家"},
    "1721": {"ranking": "電鍍化學 台灣 #1", "tech": "三晃化成、電鍍藥水", "moat": "半導體 + PCB 電鍍化學必備"},
    "1795": {"ranking": "學名藥 台灣 #1", "tech": "美時製藥、台灣最大學名藥廠", "moat": "GLP-1 仿製藥卡位"},
    "2458": {"ranking": "觸控 IC 全球 #2", "tech": "義隆 觸控板 + 生物辨識", "moat": "筆電觸控板全球市占 50%+"},
    "8103": {"ranking": "連接器 前十", "tech": "瀚荃電源連接器、車用連接器", "moat": "EV 充電連接器切入"},
    "6505": {"ranking": "石化 台塑集團", "tech": "台塑化煉油 + 石化", "moat": "台塑集團綜合能源"},
    "1304": {"ranking": "塑膠粒 前五", "tech": "台聚 PE / PS / EVA", "moat": "台聚集團母公司"},
    "3455": {"ranking": "AOI 檢測設備 前三", "tech": "由田 AI AOI 光學檢測", "moat": "半導體 + 面板 AOI"},
    "3576": {"ranking": "太陽能模組 前三", "tech": "聯合再生、太陽能系統", "moat": "離岸與地面型電廠"},
    "6667": {"ranking": "半導體設備 前十", "tech": "信紘科潔淨室 + 化學供應", "moat": "TSMC 海外擴廠受惠"},
    "6175": {"ranking": "鋁電解電容 前十", "tech": "立敦電容", "moat": "被動元件集團"},
    "2419": {"ranking": "網通 前十", "tech": "仲琦 Cable Modem、衛星 Gateway", "moat": "北美網通市場"},
    "4908": {"ranking": "光通訊 前十", "tech": "前鼎高速光收發模組", "moat": "低軌衛星光模組卡位"},
    "6153": {"ranking": "軟板 FPC 台灣 #3", "tech": "嘉聯益 Apple iPhone FPC", "moat": "蘋果折疊機軟板卡位"},
    "9933": {"ranking": "工程顧問 台灣 #1", "tech": "中鼎工程、石化 + 核能", "moat": "國家級基礎建設主力"},
    "6116": {"ranking": "面板 台灣 #3", "tech": "彩晶 DTV 驅動 + 車用面板", "moat": "中尺寸面板利基"},
    "6206": {"ranking": "飛捷 POS 系統 #1", "tech": "POS 零售系統、AI 邊緣運算", "moat": "北美零售 POS 獨家"},
    "3437": {"ranking": "LED 磊晶 前五", "tech": "榮創 Mini LED 背光、車用 LED", "moat": "富采集團、Apple Vision Pro 供應"},
    "3049": {"ranking": "光電薄膜 前十", "tech": "和鑫光電玻璃 + 面板背板", "moat": "面板上游薄膜材料"},
    "4909": {"ranking": "PCB 鑽孔 前三", "tech": "新復興 PCB 機械加工", "moat": "AI 伺服器 PCB 鑽孔代工受惠"},
    "1609": {"ranking": "電線電纜 前五", "tech": "大亞電纜 + 風電電纜", "moat": "離岸風電海底電纜卡位"},
    "6165": {"ranking": "AI 安防 前十", "tech": "浪凡 AI 影像監控", "moat": "智慧城市項目導入"},
    "1710": {"ranking": "EG 乙二醇 台灣 #1", "tech": "東聯化學、石化中游", "moat": "PET 原料核心"},
    "1909": {"ranking": "工業用紙 台灣 #3", "tech": "榮成瓦楞紙箱", "moat": "電商物流紙箱受惠"},
    "3552": {"ranking": "車用影像 全球 #1", "tech": "同致盲點 + 環景影像", "moat": "北美車廠 OEM 首選"},
    "2617": {"ranking": "散裝航運 前十", "tech": "台航海岬型船隊", "moat": "BDI 強勢受惠"},
    "6806": {"ranking": "綠能 EPC 台灣 #1", "tech": "森崴能源太陽能 + 風電建置", "moat": "政府標案受惠"},
    "1612": {"ranking": "電線電纜 前十", "tech": "宏泰電纜", "moat": "電網基建受惠"},
    "3622": {"ranking": "觸控模組 前五", "tech": "洋華電子觸控螢幕", "moat": "車用 + 工控觸控"},
    "6203": {"ranking": "電源供應器 前十", "tech": "海韻電源", "moat": "電競 / 伺服器電源"},
    "2743": {"ranking": "旅遊 台灣 #2", "tech": "山富旅行社、海外團費", "moat": "團費出團量前三"},
    "4168": {"ranking": "生醣藥物 前五", "tech": "醣聯生技癌症用藥", "moat": "生技早期研發"},
    "1730": {"ranking": "家清用品 前五", "tech": "花仙子、家用香氛", "moat": "通路品牌強"},
    "2712": {"ranking": "飯店 台灣 #5", "tech": "遠雄來來飯店、宴會", "moat": "北區飯店業者"},
    "8443": {"ranking": "鋼鐵製造 前十", "tech": "阿瘦皮鞋 — 應為皮鞋代理", "moat": "通路布局"},
    "6187": {"ranking": "半導體設備 前十", "tech": "萬潤半導體封測設備", "moat": "點膠、打線設備"},
    "4967": {"ranking": "記憶體模組 前五", "tech": "十銓 DDR5 / SSD 模組", "moat": "電競記憶體品牌"},
    "8358": {"ranking": "銅箔 前十", "tech": "金居銅箔基板原料", "moat": "HVLP 銅箔卡位"},
    "6147": {"ranking": "封測 前十", "tech": "頎邦 COF 軟板封測", "moat": "手機 Driver IC 封測"},
    "3645": {"ranking": "PI 膜 台灣 #1", "tech": "達邁電子級 PI 薄膜", "moat": "FPC 基材、OLED 卡位"},
    "6739": {"ranking": "半導體設備系統 整合", "tech": "竹陞科技廠務 AI", "moat": "TSMC 供應商"},
    "8480": {"ranking": "成衣 越南代工 前十", "tech": "泰昇-KY 越南成衣廠", "moat": "Uniqlo / Gap 供應"},
    "4908b_dup": {},  # 已定義
    "1907": {"ranking": "工業用紙 台灣 #1", "tech": "永豐餘紙業 + ESG", "moat": "榮成之上產能第一"},
    "1305": {"ranking": "塑膠粒 前五", "tech": "華夏 PVC / PS", "moat": "台塑集團相關"},
    "1507": {"ranking": "電梯 台灣 #1", "tech": "永大電梯、日立合作", "moat": "公共建築電梯主力"},
    "4804": {"ranking": "車用連接器", "tech": "大略-KY 車用訊號連接", "moat": "EV 線束切入"},
    "8497": {"ranking": "AI 教育 + 資訊產品", "tech": "倍微科技零組件 + 軟體", "moat": "電腦整機 + AI 應用"},
    "6214": {"ranking": "系統整合 台灣 #1", "tech": "精誠資訊 SI + 資安", "moat": "政府 + 金融 SI 主力"},
    "6112": {"ranking": "資訊通路 前五", "tech": "聚碩 IBM / Dell 代理", "moat": "企業伺服器通路"},
    "6682": {"ranking": "AI 研發 新秀", "tech": "旭暉應材先進封裝材料", "moat": "CoWoS 材料切入"},

    # ═══════════ Round 5（loop 第三輪）═══════════
    "5439": {"ranking": "PCB 鑽孔 前三", "tech": "高技 HDI 鑽孔加工", "moat": "AI 伺服器 PCB 高階鑽孔受惠"},
    "8150": {"ranking": "封測 前十", "tech": "南茂記憶體封測、LCD Driver", "moat": "旺宏 + 南亞科封測主力"},
    "2357": {"ranking": "筆電品牌 全球 #5", "tech": "華碩 ROG 電競 + AI PC + 伺服器", "moat": "主機板全球 #1，AI 伺服器新引擎"},
    "6271": {"ranking": "CIS 影像感測封裝 全球 #1", "tech": "同欣電 CMOS 影像封裝", "moat": "Sony / OmniVision 獨家封裝"},
    "2485": {"ranking": "衛星網通 前五", "tech": "兆赫衛星 Gateway + 路由器", "moat": "低軌衛星地面站"},
    "2376": {"ranking": "顯示卡 全球 #3 + AI 伺服器", "tech": "技嘉電競顯卡 + B200 伺服器", "moat": "NVIDIA 合作深、自有品牌"},
    "3227": {"ranking": "CMOS 影像 IC 全球 #3", "tech": "原相滑鼠感測 IC、遊戲主機", "moat": "Logitech 滑鼠獨家供應"},
    "4739": {"ranking": "鋰電池正極材料 前三", "tech": "康普鈷 / 鋰化學品", "moat": "Panasonic / Tesla 電池供應"},
    "3706": {"ranking": "伺服器 ODM 前十 + 網通", "tech": "神達伺服器 + Getac 強固電腦", "moat": "美國 / 日本客戶"},
    "4906": {"ranking": "企業網通 前五", "tech": "正文科技 AP + 路由器 + 衛星", "moat": "衛星設備切入"},
    "6278": {"ranking": "面板組件 前十", "tech": "台表科 SMT + 面板模組", "moat": "面板供應鏈關鍵"},
    "2472": {"ranking": "鋁電解電容 前五", "tech": "立隆電子、車用電容", "moat": "EV + 工業電源受惠"},
    "6877": {"ranking": "半導體 / PCB 檢測設備", "tech": "鏵友益 AOI 檢測", "moat": "AI PCB 高階檢測"},
    "6664": {"ranking": "PCB 曝光設備 前三", "tech": "群翊 PCB 曝光機台", "moat": "AI PCB 設備升級"},
    "4989": {"ranking": "CCL / PCB 前十", "tech": "榮科銅箔基板", "moat": "PCB 中游材料"},
    "6217": {"ranking": "探針卡 前五", "tech": "中探針 MEMS 探針", "moat": "半導體測試升級受惠"},
    "5234": {"ranking": "OLED 顯示材料 台灣 #1", "tech": "達興材料、半導體化學品", "moat": "友達 / 群創 OLED 獨家"},
    "4960": {"ranking": "LCD 偏光板 前五", "tech": "誠美材偏光板", "moat": "面板關鍵光學材料"},
    "5434": {"ranking": "半導體耗材通路 台灣 #1", "tech": "崇越特氣 + 晶圓化學品代理", "moat": "TSMC 供應鏈關鍵代理"},
    "1528": {"ranking": "工具機 前十", "tech": "恩德自動工具機", "moat": "精密加工中心"},
    "2467": {"ranking": "半導體烘烤設備 前三", "tech": "志聖科技光阻烤箱、OLED 烤箱", "moat": "面板 + 半導體設備"},
    "2489": {"ranking": "顯示器組裝 前五", "tech": "瑞軒 Vizio 美國市場", "moat": "北美電視市佔前三"},
    "6909": {"ranking": "氣體偵測 前三", "tech": "創控科技廢氣 / 污染防治", "moat": "半導體廠氣體監測"},
    "4577": {"ranking": "PCB 製程設備 前十", "tech": "達航科技 PCB 鑽孔", "moat": "HDI 鑽孔設備"},
    "6244": {"ranking": "太陽能電池 前三", "tech": "茂迪太陽能模組 + 系統", "moat": "政府標案受惠"},
    "2375": {"ranking": "鉭電容 前五", "tech": "智寶鉭質電容", "moat": "特殊電容利基"},
    "1312": {"ranking": "EPS 塑膠 台灣 #1", "tech": "國喬石化 EPS / ABS", "moat": "苯乙烯中游"},
    "2426": {"ranking": "LED 磊晶 前十", "tech": "鼎元 LED 晶粒", "moat": "車用 LED 利基"},
    "1308": {"ranking": "EVA 塑膠 台灣 #1", "tech": "亞聚 EVA / LDPE", "moat": "太陽能封裝 EVA 獨家"},
    "8936": {"ranking": "水處理工程 台灣 #1", "tech": "國統水處理 + 再生水", "moat": "半導體廠用水擴廠受惠"},
    "4526": {"ranking": "工具機 前十", "tech": "東台精機立式加工中心", "moat": "航太 / EV 加工"},
    "3704": {"ranking": "網通 Gateway 前五", "tech": "合勤控企業網通 + 資安", "moat": "全球網通前十"},
    "2014": {"ranking": "熱軋鋼 台灣 #3", "tech": "中鴻碳鋼熱軋", "moat": "中鋼集團"},
    "7556": {"ranking": "IC 老化測試 前三", "tech": "意德士科技 Burn-in 設備", "moat": "AI IC 可靠度測試"},
    "6756": {"ranking": "USB 控制 IC 全球 #3", "tech": "威鋒 USB 4 / TB 控制 IC", "moat": "AMD 主機板 USB 獨家"},
    "3078": {"ranking": "電源供應器 前十", "tech": "僑威電腦電源 + 伺服器", "moat": "工控電源利基"},
    "6412": {"ranking": "電源供應器 前五", "tech": "群電電源 + BBU", "moat": "AI 伺服器 BBU 切入"},
    "2504": {"ranking": "預拌混凝土 台灣 #2", "tech": "國產建材實業", "moat": "北台灣工程主力"},
    "6821": {"ranking": "電感 前十", "tech": "聯寶電子電感 + 濾波器", "moat": "AI DC + 車用電感"},
    "4711": {"ranking": "螢光劑 台灣 #1", "tech": "永光化學螢光增白劑", "moat": "紡織品增白獨家"},
    "4714": {"ranking": "半導體化學品 前十", "tech": "永捷科技、電子化學品", "moat": "半導體材料切入"},
    "6111": {"ranking": "老牌遊戲 前十", "tech": "大宇資訊 仙劍 / 軒轅劍 IP", "moat": "IP 授權收入穩定"},
    "4164": {"ranking": "放射治療設備 台灣 #1", "tech": "承業醫質子治療設備", "moat": "癌症放射治療獨家代理"},
    "2104": {"ranking": "合成橡膠 台灣 #1", "tech": "國泰橡膠 SBR / BR", "moat": "輪胎原料核心"},
    "2520": {"ranking": "營建 台灣前十", "tech": "冠德建設商辦 + 住宅", "moat": "北部都更案件多"},
    "2031": {"ranking": "鋼鐵 前十", "tech": "新鋼碳鋼", "moat": "中盤熱軋鋼商"},
    "6269": {"ranking": "FPC 軟板 台灣 #1", "tech": "台郡 iPhone 主 FPC 供應", "moat": "蘋果折疊機軟板核心"},
    "2419": {"ranking": "網通 Cable Modem", "tech": "仲琦北美 Cable + 衛星", "moat": "北美有線電視網通主力"},

    # ═══════════ Round 6（loop 第三輪）═══════════
    "3491": {"ranking": "毫米波 / 衛星 RF 台灣 #1", "tech": "昇達科毫米波 + CPO 濾波器", "moat": "低軌衛星 + CPO 雙切入"},
    "4749": {"ranking": "2nm 光阻 千金股", "tech": "新應材 EUV 光阻 + ArF 光阻", "moat": "日廠唯一強勁對手"},
    "6257": {"ranking": "封測 前十", "tech": "矽格 Flip-chip + COF 封裝", "moat": "驅動 IC 封測利基"},
    "7734": {"ranking": "半導體壓著設備", "tech": "印能科技 CoWoS 壓著機台", "moat": "先進封裝設備新秀"},
    "3030": {"ranking": "半導體 AOI 測試 前三", "tech": "德律 AOI + ATE 測試", "moat": "IC 封測檢測主力"},
    "3376": {"ranking": "鉸鏈 全球 #1", "tech": "新日興筆電 / 摺疊手機鉸鏈", "moat": "蘋果摺疊 iPhone 獨家供應"},
    "6282": {"ranking": "電源供應器 前十", "tech": "康舒 AC/DC 電源", "moat": "仁寶集團伺服器電源"},
    "4919": {"ranking": "MCU 台灣 #1", "tech": "新唐 Arm MCU + 車用 IC", "moat": "車用 + 工控 MCU 主力"},
    "3013": {"ranking": "伺服器機殼 前五", "tech": "晟銘電 Rackmount 機殼", "moat": "緯創集團伺服器代工"},
    "1773": {"ranking": "電子化學品 台灣 #1", "tech": "勝一半導體化學品 + 電子級溶劑", "moat": "TSMC 擴廠受惠"},
    "8027": {"ranking": "半導體設備 前十", "tech": "鈦昇 Probe Card + 封測設備", "moat": "高階測試設備利基"},
    "3289": {"ranking": "IC 可靠度驗證 台灣 #1", "tech": "宜特 IC 故障分析 + 材料驗證", "moat": "車用 + AI IC 驗證湧入"},
    "2353": {"ranking": "筆電品牌 全球 #6", "tech": "宏碁 Predator 電競 + AI PC", "moat": "全球 PC 前六大品牌"},
    "6104": {"ranking": "USB IC 前五", "tech": "創惟 USB 控制 IC", "moat": "北美品牌 USB 方案主力"},
    "5475": {"ranking": "PCB 前十", "tech": "德宏工業 PCB", "moat": "消費電子 PCB 利基"},
    "2385": {"ranking": "電腦周邊 前三", "tech": "群光鍵盤 + 鏡頭 + 電源", "moat": "筆電鍵盤全球主供"},
    "6202": {"ranking": "MCU 前五", "tech": "盛群 Arm MCU + 觸控 IC", "moat": "消費 + 工控 MCU 雙主軸"},
    "4916": {"ranking": "網通 前十", "tech": "事欣科網通 + 車載", "moat": "EMS 雲端通訊設備"},
    "6588": {"ranking": "光通訊 前十", "tech": "東典光電光纖通訊", "moat": "光通訊被動元件"},
    "3588": {"ranking": "電源管理 IC 前五", "tech": "通嘉 LED 驅動 + PMIC", "moat": "LED 照明 IC 獨家"},
    "6683": {"ranking": "半導體測試座 前三", "tech": "雍智科技 Probe Socket", "moat": "先進封裝測試升級"},
    "2605": {"ranking": "散裝航運 前五", "tech": "新興海運巴拿馬型", "moat": "BDI 強勢配息"},
    "6121": {"ranking": "電池模組 台灣 #1", "tech": "新普筆電電池 + 儲能 BESS", "moat": "蘋果 MacBook 獨家供應"},
    "2428": {"ranking": "熱敏電阻 全球 #2", "tech": "興勤 NTC / PTC 熱敏", "moat": "車用 + EV 熱保護"},
    "2006": {"ranking": "鋼鐵 前十", "tech": "東和鋼鐵電爐", "moat": "ESG 低碳鋼鐵"},
    "1608": {"ranking": "電線電纜 前三", "tech": "華榮電線 + 銅線", "moat": "電網基建 + AI DC 線纜"},
    "2548": {"ranking": "營建 台灣前五", "tech": "華固建設商辦 + 都更", "moat": "北部都更指標廠商"},
    "6491": {"ranking": "隱形眼鏡 台灣 #2", "tech": "晶碩日拋 + 美瞳", "moat": "精華光學之外主力"},
    "8215": {"ranking": "面板材料 前十", "tech": "明基材偏光板 + PCB", "moat": "面板上游材料"},
    "7402": {"ranking": "無人機 / 影像 前十", "tech": "邑錡運動相機 + 軍用無人機", "moat": "國防無人機切入"},
    "2392": {"ranking": "連接器 前五", "tech": "正崴電子連接器 + iPhone Cable", "moat": "蘋果 Lightning / Type-C 線材"},
    "7810": {"ranking": "封測設備 前十", "tech": "捷創科技 IC 封測設備", "moat": "先進封裝擴產受惠"},
    "1434": {"ranking": "紡織輪胎簾布 前三", "tech": "福懋 PET 簾布 + 聚酯", "moat": "輪胎骨架紗主供"},
    "6235": {"ranking": "鎂鋁合金機殼 前五", "tech": "華孚筆電 / 手機鎂合金", "moat": "3C 金屬機殼利基"},
    "4174": {"ranking": "抗癌新藥 台灣領先", "tech": "浩鼎乳癌 OBI-822", "moat": "台灣新藥明星股"},
    "6224": {"ranking": "過電流保護 PPTC 前三", "tech": "聚鼎可恢復保險絲", "moat": "電子元件保護利基"},
    "9955": {"ranking": "再生金屬 前十", "tech": "佳龍廢電子回收貴金屬", "moat": "ESG 循環經濟"},
    "1218": {"ranking": "食品 前十", "tech": "泰山飲料 + 食用油", "moat": "冷藏飲料通路"},
    "4157": {"ranking": "抗生素新藥", "tech": "太景-KY 抗生素 Taigexyn", "moat": "全球上市抗生素"},
    "1537": {"ranking": "機車電池 全球 #1", "tech": "廣隆 Yuasa 授權 UPS 電池", "moat": "UPS + 機車電池雙引擎"},
    "6259": {"ranking": "被動元件 前十", "tech": "百徽電感 + 電容", "moat": "工控 + 車用元件"},
    "6576": {"ranking": "新藥 前十", "tech": "逸達攝護腺癌新藥", "moat": "泌尿癌新藥"},
    "1702": {"ranking": "家清食品 台灣 #2", "tech": "南僑 泡沫洗手 + 冷凍", "moat": "家用洗劑 + 餐飲冷凍"},
    "3027": {"ranking": "綠能系統 前十", "tech": "盛達光電 + 網通", "moat": "智慧電網切入"},
    "2107": {"ranking": "橡膠塑膠 前十", "tech": "厚生塑膠管材", "moat": "水處理 + 基建管材"},
    "2748": {"ranking": "飯店 台灣前十", "tech": "雲品溫泉度假飯店", "moat": "日月潭度假"},
    "4726": {"ranking": "生物藥 CDMO", "tech": "永昕抗體新藥委外", "moat": "生技 CDMO 前五"},

    # ═══════════ Round 7（loop 第四輪）═══════════
    "6531": {"ranking": "DRAM IC 設計 前五", "tech": "愛普 低功耗 DRAM + 記憶體模組", "moat": "AI 伺服器 DDR5 切入"},
    "3211": {"ranking": "電池模組 前三", "tech": "順達工科 筆電 + 儲能電池", "moat": "蘋果 MacBook 供應鏈"},
    "2301": {"ranking": "電源供應 + LED 全球 #2", "tech": "光寶科電源 + 光學元件", "moat": "伺服器電源 + Mini LED 雙引擎"},
    "5289": {"ranking": "工業級 SSD 台灣 #1", "tech": "宜鼎國際工控 / 醫療 SSD", "moat": "利基型 SSD 高毛利"},
    "8271": {"ranking": "記憶體模組 前五", "tech": "宇瞻 DRAM / SSD 模組", "moat": "工業與消費雙市場"},
    "3006": {"ranking": "DRAM 設計 前三", "tech": "晶豪科 Niche DRAM", "moat": "車用 + 工控利基記憶體"},
    "6213": {"ranking": "CCL 銅箔基板 前五", "tech": "聯茂 高速 CCL Megtron", "moat": "AI 伺服器 CCL 漲價受惠"},
    "2324": {"ranking": "筆電 ODM 全球前三", "tech": "仁寶 Chromebook + AI PC", "moat": "Google / HP / Lenovo 主供"},
    "3587": {"ranking": "IC 故障分析 前三", "tech": "閎康 材料分析 + 可靠度", "moat": "車用晶片驗證湧入"},
    "2441": {"ranking": "封測 前十", "tech": "超豐 IC 封測", "moat": "車用 IC 封測主力"},
    "4938": {"ranking": "筆電 ODM 全球前五", "tech": "和碩 iPhone + AI 伺服器", "moat": "蘋果第二大組裝廠"},
    "5351": {"ranking": "車用 IC 前十", "tech": "鉅創車用 LCD Driver + MCU", "moat": "車用顯示 IC 主力"},
    "7751": {"ranking": "IC 設計 前十", "tech": "竑騰 MCU / Timing IC", "moat": "消費電子 IC 利基"},
    "6426": {"ranking": "光通訊模組 前十", "tech": "統新光通訊 被動元件", "moat": "矽光子 CPO 卡位"},
    "3605": {"ranking": "連接器 前五", "tech": "宏致企業電源 / 信號連接器", "moat": "車用 + 家電連接器"},
    "6409": {"ranking": "UPS 前三", "tech": "旭隼科技 UPS + 儲能 PCS", "moat": "資料中心 UPS + 儲能 BESS"},
    "8054": {"ranking": "電源供應 前十", "tech": "安力-KY 電源模組 + 車用", "moat": "EV 快充電源切入"},
    "8261": {"ranking": "功率 MOSFET 前五", "tech": "富鼎 MOSFET + SiC", "moat": "EV / 電源 IC 功率元件"},
    "1504": {"ranking": "重電馬達 全球 #5", "tech": "東元馬達 + 機器人 + 重電", "moat": "重電三雄之一"},
    "3005": {"ranking": "堅固筆電 全球 #2", "tech": "神基 Getac 軍規筆電", "moat": "國防 / 警消 / 醫療市場"},
    "6414": {"ranking": "工控 IPC 前五", "tech": "樺漢科技工業電腦 + 伺服器", "moat": "鴻海系工控旗艦"},
    "4973": {"ranking": "記憶卡 / 隨身碟 前五", "tech": "廣穎電通 Silicon Power", "moat": "全球 SSD / 記憶卡品牌"},
    "6691": {"ranking": "半導體廠務 前三", "tech": "洋基工程 潔淨室機電", "moat": "TSMC 擴廠獨家"},
    "2354": {"ranking": "散熱機殼 前五", "tech": "鴻準鎂鋁合金 + 散熱模組", "moat": "蘋果金屬機殼供應"},
    "4721": {"ranking": "鋰電池正極材料 前三", "tech": "美琪瑪鈷 / 鎳金屬回收", "moat": "Panasonic 供應鏈"},
    "6830": {"ranking": "IC 故障分析 前五", "tech": "汎銓科技失效分析", "moat": "AI 晶片驗證受惠"},
    "3093": {"ranking": "PCB 前十", "tech": "港建興業 HDI PCB", "moat": "消費電子 PCB 利基"},
    "8932": {"ranking": "PET 瓶 全球前三", "tech": "宏全國際 飲料包裝", "moat": "可口可樂 / 統一獨家"},
    "2493": {"ranking": "PCB 連接器 前十", "tech": "揚博科技 PCB 端子", "moat": "連接器利基"},
    "1514": {"ranking": "變壓器 前五", "tech": "亞力電機 變壓器 + 配電", "moat": "重電 + 電網升級受惠"},
    "4766": {"ranking": "接著劑 台灣 #1", "tech": "南寶樹脂接著劑 + 塗料", "moat": "運動鞋 / 家具接著劑獨家"},
    "3014": {"ranking": "驅動 IC 前五", "tech": "聯陽 TFT / 觸控 Driver IC", "moat": "顯示 IC 利基"},
    "6443": {"ranking": "太陽能電池 前三", "tech": "元晶太陽能模組", "moat": "台灣太陽能模組主力"},
    "8464": {"ranking": "GaN MOCVD 全球獨家", "tech": "億豐 Google Android XR GaN 供應", "moat": "AI 眼鏡 GaN 獨家"},
    "6150": {"ranking": "顯卡品牌 前十", "tech": "撼訊科技 AMD 顯卡合作", "moat": "AMD Radeon 台灣獨家代工"},
    "2633": {"ranking": "高鐵 台灣 #1", "tech": "台灣高鐵 北高高速運輸", "moat": "獨家高鐵營運權"},
    "2457": {"ranking": "電源供應 前十", "tech": "飛宏電源 + EV 充電模組", "moat": "EV 充電樁卡位"},
    "8043": {"ranking": "被動元件 前十", "tech": "蜜望實電阻 + 電容", "moat": "工控 + 車用元件"},
    "3022": {"ranking": "石英元件 前十", "tech": "IC 晶技相關精密元件", "moat": "5G / 衛星時脈元件"},
    "5521": {"ranking": "水資源工程 前五", "tech": "工信工程水處理 + 土木", "moat": "TSMC 廠務工程受惠"},
    "3339": {"ranking": "LED 磊晶 前十", "tech": "泰谷光電 LED 磊晶", "moat": "Mini LED 卡位"},
    "6716": {"ranking": "MCU 前十", "tech": "應廣 MCU + PMIC", "moat": "消費電子 MCU 利基"},
    "4764": {"ranking": "半導體特氣 前五", "tech": "雙鍵化工 特殊氣體 + 電子級化學", "moat": "半導體擴廠受惠"},
    "4908b_dup": {},  # 已存在
    "8045_dup": {},  # placeholder

    # ═══════════ Round 8（loop 第五輪）═══════════
    "3450": {"ranking": "光通訊模組 前五", "tech": "聯鈞光通訊 VCSEL", "moat": "AI DC 光模組升級"},
    "2316": {"ranking": "PCB 前十", "tech": "楠梓電 IC 載板 + HDI", "moat": "高階 PCB 產能擴張"},
    "7822": {"ranking": "探針卡 前五", "tech": "倍利科技 MEMS 探針", "moat": "先進封裝測試"},
    "3023": {"ranking": "連接器 前五", "tech": "信邦電子 連接器 + 醫療設備", "moat": "車用 + 醫療連接多角化"},
    "5243": {"ranking": "金屬鑄造 前五", "tech": "乙盛-KY 背光模組 + 鎂合金", "moat": "蘋果供應鏈"},
    "6209": {"ranking": "光學元件 前五", "tech": "今國光 鏡頭 + 矽光子", "moat": "CPO / 光通訊鏡片卡位"},
    "2501": {"ranking": "建設 前十", "tech": "國建 北部商辦 + 住宅", "moat": "土地資產豐厚"},
    "6894": {"ranking": "綠能設備 前十", "tech": "衛司特太陽能 EPC", "moat": "離岸風電運維"},
    "2023": {"ranking": "熱軋鋼 前十", "tech": "燁輝鋼鐵 熱軋 + 冷軋", "moat": "汽車鋼板主供"},
    "1591": {"ranking": "精密機構 前十", "tech": "駿吉-KY 機械零件", "moat": "工具機零件利基"},
    "1618": {"ranking": "電線電纜 前十", "tech": "合機線纜", "moat": "電網 + 風電受惠"},
    "4736": {"ranking": "血糖儀 全球 #3", "tech": "泰博科技 血糖 + 體溫計", "moat": "IVD 全球品牌"},
    "3467": {"ranking": "晶圓再生 全球 #1", "tech": "台灣精材再生晶圓", "moat": "TSMC 獨家再生晶圓"},
    "1104": {"ranking": "水泥 前五", "tech": "環泥水泥 + 生技", "moat": "中部水泥主力"},
    "3555": {"ranking": "PCB 材料 前十", "tech": "博士旺 PCB 銅箔", "moat": "中游材料利基"},
    "2534": {"ranking": "建設 前十", "tech": "宏盛建設 商辦 + 住宅", "moat": "北部推案量大"},
    "3546": {"ranking": "遊戲股 前五", "tech": "宇峻奧汀 仙劍 / 奇蹟 IP", "moat": "老牌遊戲 IP 授權"},
    "9925": {"ranking": "建設 前二十", "tech": "新美齊 住宅推案", "moat": "土地開發利基"},
    "4555": {"ranking": "工具機 前十", "tech": "台勵福 鍛造設備", "moat": "鍛壓機械主力"},
    "3607": {"ranking": "3C 鎂合金 前十", "tech": "谷崧 筆電零件 + 鎂合金", "moat": "筆電機殼前十"},
    "3066": {"ranking": "LED 封裝 前十", "tech": "李洲 LED + 車用", "moat": "車用 LED 利基"},
    "5228": {"ranking": "電感 前十", "tech": "鈺鎧 電感 + 變壓器", "moat": "AI 伺服器電感供應"},
    "3564": {"ranking": "網通 前十", "tech": "其陽 企業路由器", "moat": "中小企業網通市場"},
    "2032": {"ranking": "鋼鐵 前十", "tech": "新鋼 型鋼 + 建築鋼構", "moat": "基建鋼材利基"},
    "2314": {"ranking": "衛星通訊 台灣歷史 #1", "tech": "台揚科技 衛星地面站 + 5G", "moat": "衛星通訊老牌廠商"},
    "1109": {"ranking": "水泥 前十", "tech": "信大水泥 + 生態池", "moat": "水泥中小型廠"},
    "8467": {"ranking": "3D 列印粉末 前五", "tech": "波力-KY 金屬粉末 + 球化", "moat": "航太 / 醫材 3D 列印"},
    "6464": {"ranking": "綠能材料 前十", "tech": "永豐實 PET 瓶胚 + 太陽能封裝", "moat": "多角化新材料"},
    "2109": {"ranking": "輪胎 前五", "tech": "華豐橡膠 輪胎 + 工業輪胎", "moat": "工業機械輪胎"},
    "4426": {"ranking": "塑膠射出 前十", "tech": "利勤實業 3C / 醫材外殼", "moat": "精密射出成型"},
    "2227": {"ranking": "汽車銷售 台灣前五", "tech": "裕日車 日產 Nissan 台灣代理", "moat": "日系車代理商"},
    "1521": {"ranking": "車燈 前五", "tech": "大億交通工業 車燈 + 鈑金", "moat": "OEM 車燈供應"},
    "3673": {"ranking": "觸控面板 台灣 #1", "tech": "TPK-KY 宸鴻 觸控模組", "moat": "蘋果 iPad 獨家"},
    "8016": {"ranking": "驅動 IC 前五", "tech": "矽創電子 LCD Driver + Timing", "moat": "中小尺寸面板 IC 主力"},
    "6907": {"ranking": "MCU 前十", "tech": "雅特力-KY Arm MCU", "moat": "ST / NXP 之外台廠選擇"},
    "6451": {"ranking": "CIS 封裝 前五", "tech": "訊芯-KY 光通訊封裝", "moat": "矽光子 + CPO 切入"},
    "6719": {"ranking": "電池材料 前十", "tech": "力瑋實業 鋰電池正極", "moat": "EV 電池材料"},
    "3221": {"ranking": "晶振石英 前十", "tech": "台嘉碩 晶振元件", "moat": "車用 + 網通晶振"},
    "6829": {"ranking": "精密機構 前十", "tech": "千附精密 半導體潔淨設備零件", "moat": "TSMC 廠務零件"},
    "2456": {"ranking": "電感 全球 #3", "tech": "奇力新 電感 + 磁性元件", "moat": "車用 + AI DC 電感"},
    "4120": {"ranking": "生技通路 前五", "tech": "友華生技醫材代理", "moat": "醫美 + 健康食品代理"},
    "1902": {"ranking": "工業用紙 前十", "tech": "台紙瓦楞紙", "moat": "電商物流受惠"},
    "4551": {"ranking": "精密機械 前十", "tech": "智伸科 車用零件 + 精密螺絲", "moat": "EV + 航太加工"},
    "5765": {"ranking": "醫材 前十", "tech": "雃博 呼吸器 + 氣墊床", "moat": "居家醫材主力"},
    "6419": {"ranking": "工控伺服器 前十", "tech": "京晨科 IPC + 伺服器", "moat": "IPC 利基"},
    "8374": {"ranking": "自動化代理 前五", "tech": "羅昇 西門子 / FANUC 代理", "moat": "工業自動化整合商"},

    # ═══════════ Round 9（loop 第六輪 — 掃尾）═══════════
    "1103": {"ranking": "水泥 前十", "tech": "嘉泥 水泥 + 能源投資", "moat": "嘉新集團水泥業務"},
    "1229": {"ranking": "飼料食品 前十", "tech": "聯華實業 麵粉 / 飼料", "moat": "烘焙原料主力"},
    "1325": {"ranking": "化工口罩 前十", "tech": "恆大化學 防疫口罩", "moat": "不織布切入"},
    "1439": {"ranking": "紡織 前十", "tech": "中和羊毛 針織布", "moat": "中高階羊毛布利基"},
    "1444": {"ranking": "紡織 前十", "tech": "力麗 聚酯纖維", "moat": "PET 紗線主力"},
    "1453": {"ranking": "紡織 前十", "tech": "大將企業 機能布", "moat": "運動機能紡織"},
    "1457": {"ranking": "紡織 前十", "tech": "宜進紡織 針織布", "moat": "高機能紗線"},
    "1517": {"ranking": "馬達 前十", "tech": "利奇機械 工業馬達", "moat": "工業自動化馬達"},
    "1525": {"ranking": "汽車零件 前五", "tech": "江申工業 車身沖壓件", "moat": "國產汽車鈑金供應"},
    "1527": {"ranking": "螺絲 前五", "tech": "鑽全實業 精密螺絲", "moat": "汽車 + 航太螺絲"},
    "1533": {"ranking": "車用電機 前五", "tech": "車王電子 汽車起動馬達", "moat": "EV 動力零件切入"},
    "1583": {"ranking": "工具機 前三", "tech": "程泰 車床 + 加工中心", "moat": "精密車削機龍頭"},
    "1589": {"ranking": "風機機殼 全球 #1", "tech": "永冠-KY 風力發電機殼鑄造", "moat": "全球風機零件獨家"},
    "1598": {"ranking": "健身器材 前十", "tech": "岱宇國際 跑步機 / 飛輪", "moat": "北美健身器材品牌"},
    "1611": {"ranking": "電線 前十", "tech": "中電線纜 + 銅線", "moat": "電網基建受惠"},
    "1614": {"ranking": "家電 前十", "tech": "三洋電機 白色家電", "moat": "洗衣機 / 冰箱品牌"},
    "1709": {"ranking": "塑化 前十", "tech": "和益化工 SM / PU", "moat": "化工中游"},
    "1732": {"ranking": "家清用品 前五", "tech": "毛寶 洗衣 / 清潔劑", "moat": "通路品牌強"},
    "1760": {"ranking": "生技保健 前五", "tech": "寶齡富錦 腎臟病新藥 + 保健食品", "moat": "洗腎用藥獨家"},
    "1903": {"ranking": "紙業 前十", "tech": "士林紙業 紙板", "moat": "傳統紙業廠"},
    "2024": {"ranking": "鋼鐵 前十", "tech": "志聯工業 鋼構件", "moat": "鋼構加工"},
    "2352": {"ranking": "顯示器 ODM 全球 #2", "tech": "佳世達 明碁 Monitor + 醫材", "moat": "宏碁集團轉型多角化"},
    "2420": {"ranking": "電源供應 前十", "tech": "新巨 AC/DC 電源", "moat": "工業電源利基"},
    "2440": {"ranking": "連接器 前十", "tech": "太空梭 連接器與 cable", "moat": "消費電子連接利基"},
    "2511": {"ranking": "建設 前十", "tech": "太子建設 住宅 + 商辦", "moat": "南部推案量大"},
    "2528": {"ranking": "建設 前十", "tech": "皇普建設 住宅", "moat": "北部推案"},
    "2530": {"ranking": "建設 前十", "tech": "華建集團 住宅", "moat": "華南集團建設子公司"},
    "2545": {"ranking": "建設 前十", "tech": "皇翔建設 高端住宅", "moat": "豪宅品牌"},
    "2608": {"ranking": "物流 前十", "tech": "大榮貨運 台灣陸運", "moat": "宅配通整合"},
    "2613": {"ranking": "航運 前十", "tech": "中櫃 散裝航運", "moat": "散裝中小型船"},
    "2614": {"ranking": "投資媒體 前十", "tech": "東森國際 投資 + 航運", "moat": "多角化投資"},
    "2636": {"ranking": "國際物流 前五", "tech": "臺驊投控 海運承攬 + 空運", "moat": "貨攬業前三"},
    "2705": {"ranking": "飯店 前十", "tech": "六福旅遊 飯店 + 樂園", "moat": "六福村主題樂園"},
    "2706": {"ranking": "飯店 前十", "tech": "第一大飯店 觀光飯店", "moat": "老牌觀光飯店"},
    "2707": {"ranking": "飯店 台灣 #1", "tech": "晶華酒店 國際五星", "moat": "麗晶品牌全球授權"},
    "2719": {"ranking": "旅遊 前五", "tech": "燦星旅行社 海外旅遊", "moat": "出團量前五"},
    "2729": {"ranking": "餐飲 前十", "tech": "瓦城泰式餐飲", "moat": "泰式連鎖龍頭"},
    "2739": {"ranking": "飯店 前十", "tech": "寒舍集團 喜來登 + 艾美", "moat": "五星飯店授權"},
    "2915": {"ranking": "百貨零售 台灣 #1", "tech": "潤泰全 大潤發 + 南山人壽", "moat": "大賣場 + 金融"},
    "3015": {"ranking": "電源供應 前五", "tech": "全漢電源 伺服器 + 消費", "moat": "AI 伺服器電源受惠"},
    "3086": {"ranking": "遊戲股 前十", "tech": "華義國際 線上遊戲運營", "moat": "中文化海外遊戲代理"},
    "3131": {"ranking": "半導體設備 前五", "tech": "弘塑科技 CMP 設備", "moat": "CMP 研磨設備主力"},
    "3167": {"ranking": "CNC 設備 前十", "tech": "大量科技 CNC + 自動化", "moat": "工具機自動化"},
    "3229": {"ranking": "PCB 材料 前十", "tech": "晟鈦實業 PCB 電鍍材料", "moat": "PCB 中游材料"},
    "3260": {"ranking": "記憶體模組 前三", "tech": "威剛 DDR / SSD / 記憶卡", "moat": "全球前三記憶體模組"},
    "3356": {"ranking": "監控 IC 前三", "tech": "奇偶科技 DVR / IP Cam IC", "moat": "監控晶片龍頭"},
    "3413": {"ranking": "半導體設備 前五", "tech": "京鼎精密 熱處理爐 + PECVD", "moat": "半導體製程設備"},
    "3454": {"ranking": "監控 前三", "tech": "晶睿通訊 IP Cam + NVR", "moat": "全球 IP 監控前十"},
    "3535": {"ranking": "LED 驅動 前十", "tech": "晶彩科 LED Driver", "moat": "車用 LED 驅動 IC"},
    "3581": {"ranking": "半導體製程 前十", "tech": "博磊科技 半導體濾波", "moat": "磊晶設備"},
    "3583": {"ranking": "半導體設備 前五", "tech": "辛耘企業 濕製程設備", "moat": "先進製程濕蝕刻設備"},
    "3664": {"ranking": "電源模組 前十", "tech": "安瑞-KY 工業電源", "moat": "伺服器電源"},
    "3687": {"ranking": "遊戲 前十", "tech": "歐買尬 遊戲代理", "moat": "台灣老牌遊戲平台"},
    "4105": {"ranking": "新藥 前十", "tech": "東洋製藥 癌症用藥", "moat": "學名藥 + 新藥研發"},
    "4107": {"ranking": "醫材 前十", "tech": "邦特生技 透析管 + 注射針", "moat": "洗腎耗材主力"},
    "4114": {"ranking": "中藥 前十", "tech": "健喬信元 中西藥", "moat": "中藥製造 + 代理"},
    "4116": {"ranking": "醫材 前五", "tech": "明基醫 血糖儀 + 雲端醫療", "moat": "明基集團醫療"},
    "4128": {"ranking": "新藥 前十", "tech": "中天生技 Ectosome 外泌體", "moat": "再生醫療"},
    "4176": {"ranking": "醫美 前五", "tech": "佐登-KY 美容醫材", "moat": "美容連鎖"},
    "4406": {"ranking": "紡織 前十", "tech": "新昕纖 聚酯纖維", "moat": "PET 紗利基"},
    "4430": {"ranking": "紡織 前十", "tech": "耀億工業 羽絨 + 功能布", "moat": "戶外機能布"},
    "4506": {"ranking": "電梯 前五", "tech": "崇友實業 電梯", "moat": "日立 / OTIS 代理 + 自製"},
    "4532": {"ranking": "壓縮機 前五", "tech": "瑞智精密 冰箱壓縮機", "moat": "白色家電壓縮機主力"},
    "4562": {"ranking": "工具機 前十", "tech": "穎漢科技 鍛造設備", "moat": "汽車零件鍛造"},
    "4564": {"ranking": "工具機 前十", "tech": "元翎精密 工具機", "moat": "車床主力"},
    "4907": {"ranking": "電信 前十", "tech": "富宇服務股", "moat": "電信業"},
    "5341": {"ranking": "特氣代理 前十", "tech": "眾福科 電子氣體代理", "moat": "半導體廠氣體"},
    "5386": {"ranking": "觸控 前十", "tech": "青雲國際 觸控面板", "moat": "中尺寸觸控"},
    "5490": {"ranking": "設備 前十", "tech": "同亨科技 PCB 設備", "moat": "PCB 製程設備"},
    "6141": {"ranking": "PCB 前十", "tech": "柏承科技 PCB", "moat": "中階 PCB 利基"},
    "6173": {"ranking": "電容 前十", "tech": "信昌電子 電解電容", "moat": "被動元件利基"},
    "6184": {"ranking": "電源 前十", "tech": "大河 電源供應器", "moat": "電源模組"},
    "6208": {"ranking": "真空設備 前三", "tech": "日揚科技 真空幫浦", "moat": "半導體真空設備"},
    "6226": {"ranking": "LED 前十", "tech": "光鼎科技 LED 封裝", "moat": "車用 LED"},
    "6251": {"ranking": "PCB 前十", "tech": "定穎電子 車用 PCB", "moat": "車用 + 通訊 PCB"},
    "6283": {"ranking": "智慧電錶 前十", "tech": "淳安電子 電能計量晶片", "moat": "智慧電錶 IC"},
    "6504": {"ranking": "口罩不織布 前五", "tech": "南六實業 不織布", "moat": "口罩 + 濕巾主料"},
    "6513": {"ranking": "智慧電錶 前十", "tech": "柏彥科技 電錶 + NB-IoT", "moat": "智慧電錶整合"},
    "6514": {"ranking": "環保設備 前十", "tech": "芮特-KY 工業污染處理", "moat": "環保工程"},
    "6541": {"ranking": "生技 前十", "tech": "泰福-KY 生物相似藥", "moat": "抗癌生物相似藥"},
    "6572": {"ranking": "新藥 前十", "tech": "康霈生技 溶脂新藥", "moat": "醫美新藥卡位"},
    "6649": {"ranking": "綠能 前十", "tech": "泓德能源 儲能 EPC", "moat": "儲能系統整合"},
    "6679": {"ranking": "MEMS IC 前十", "tech": "鈺太科技 MEMS 麥克風 + 功放", "moat": "TWS 耳機 MEMS"},
    "6699": {"ranking": "電纜 前十", "tech": "大山電線 銅纜", "moat": "電網基建"},
    "6702": {"ranking": "保健食品 前三", "tech": "大江生醫 機能飲料 + 保健", "moat": "全球保健食品代工"},
    "6715": {"ranking": "化工 前十", "tech": "嘉基科技 電子化學品", "moat": "半導體化學品利基"},
    "6803": {"ranking": "航太 前十", "tech": "崴航 國際物流", "moat": "航空物流利基"},
    "6928": {"ranking": "無人機 前十", "tech": "攸泰科技 無人機零件", "moat": "國防無人機供應"},
    "7704": {"ranking": "半導體零件 前十", "tech": "明遠精密 半導體機件", "moat": "TSMC 廠務零件"},
    "7717": {"ranking": "光電 前十", "tech": "萊德光電-KY 光通訊", "moat": "矽光子七劍客"},
    "8067": {"ranking": "國防 前十", "tech": "志旭國際 防禦系統", "moat": "國防電子零件"},
    "8091": {"ranking": "半導體零件 前十", "tech": "翔名科技 真空零件", "moat": "半導體 / 面板零件"},
    "8433": {"ranking": "自行車 前十", "tech": "弘帆 自行車零件", "moat": "運動車配件"},
    "8923": {"ranking": "手工具 前十", "tech": "鼎炫-KY 電動工具", "moat": "美國市場工具"},
    "9919": {"ranking": "不織布 前五", "tech": "康那香 口罩 + 衛生品", "moat": "不織布衛生主力"},
    "9927": {"ranking": "稀土合金 前三", "tech": "泰銘資源 稀土回收", "moat": "稀土再生利用"},
    "9957": {"ranking": "鋼鐵 前十", "tech": "燁聯鋼鐵 不鏽鋼", "moat": "不鏽鋼利基"},
}

# 清除 placeholder（key 以 '_dup' 結尾或 value 為空）
STOCK_HIGHLIGHTS = {k: v for k, v in STOCK_HIGHLIGHTS.items() if v and not k.endswith("_dup")}
